'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication.Implementation
    
    #Region "Child"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Child
        Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation
        Private Sub OnID_ClassChanged()
            Me.___OnPropertyChanged("ID_Class")
            Me.___OnPropertyChanged("Classroom")
        End Sub
        
        Private Sub OnID_ParentChanged()
            Me.___OnPropertyChanged("ID_Parent")
            Me.___OnPropertyChanged("Parent")
        End Sub
        
        Private Sub OnID_PayChanged()
            Me.___OnPropertyChanged("ID_Pay")
            Me.___OnPropertyChanged("Payment")
        End Sub
        
        Private Property _ID_ChildImplementation() As Integer Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.ID_Child
            Get
                Return Me.ID_Child
            End Get
            Set(ByVal value As Integer)
                Me.ID_Child = value
            End Set
        End Property
        
        Private Sub OnID_ChildChanged()
            Me.___OnPropertyChanged("ID_Child")
        End Sub
        
        Private Property _NameImplementation() As String Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Name
            Get
                Return Me.Name
            End Get
            Set(ByVal value As String)
                Me.Name = value
            End Set
        End Property
        
        Private Sub OnNameChanged()
            Me.___OnPropertyChanged("Name")
        End Sub
        
        Private Property _Birth_dateImplementation() As Date Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Birth_date
            Get
                Return Me.Birth_date
            End Get
            Set(ByVal value As Date)
                Me.Birth_date = value
            End Set
        End Property
        
        Private Sub OnBirth_dateChanged()
            Me.___OnPropertyChanged("Birth_date")
        End Sub
        
        Private Property _GenderImplementation() As String Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Gender
            Get
                Return Me.Gender
            End Get
            Set(ByVal value As String)
                Me.Gender = value
            End Set
        End Property
        
        Private Sub OnGenderChanged()
            Me.___OnPropertyChanged("Gender")
        End Sub
        
        Private Property _ClassroomImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Classroom
            Get
                Return Me.Classroom
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Classroom = DirectCast(value, Global.LightSwitchApplication.Implementation.Classroom)
            End Set
        End Property
        
        Private ReadOnly Property __Classroom As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Classroom) 
            Get
                If (Me.___Classroom Is Nothing) Then
                    Me.___Classroom = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Classroom)( _
                        Me, _
                        "Classroom", _
                        New Global.System.String() {"ID_Class"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Class, Me.ID_Class), _
                        Function() Me._Classroom, _
                        Sub(e) Me._Classroom = e)
                End If
                Return Me.___Classroom
            End Get
        End Property
        
        Private ___Classroom As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Classroom)
        
        Private Property _ParentImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Parent
            Get
                Return Me.Parent
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Parent = DirectCast(value, Global.LightSwitchApplication.Implementation.Parent)
            End Set
        End Property
        
        Private ReadOnly Property __Parent As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Parent) 
            Get
                If (Me.___Parent Is Nothing) Then
                    Me.___Parent = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Parent)( _
                        Me, _
                        "Parent", _
                        New Global.System.String() {"ID_Parent"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Parent, Me.ID_Parent), _
                        Function() Me._Parent, _
                        Sub(e) Me._Parent = e)
                End If
                Return Me.___Parent
            End Get
        End Property
        
        Private ___Parent As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Parent)
        
        Private Property _PaymentImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Child.DetailsClass.IImplementation.Payment
            Get
                Return Me.Payment
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Payment = DirectCast(value, Global.LightSwitchApplication.Implementation.Payment)
            End Set
        End Property
        
        Private ReadOnly Property __Payment As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Payment) 
            Get
                If (Me.___Payment Is Nothing) Then
                    Me.___Payment = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Payment)( _
                        Me, _
                        "Payment", _
                        New Global.System.String() {"ID_Pay"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Pay, Me.ID_Pay), _
                        Function() Me._Payment, _
                        Sub(e) Me._Payment = e)
                End If
                Return Me.___Payment
            End Get
        End Property
        
        Private ___Payment As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Payment)
        
    End Class
    #End Region
    
    #Region "Classroom"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Classroom
        Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation
        Private Sub OnID_LevelChanged()
            Me.___OnPropertyChanged("ID_Level")
            Me.___OnPropertyChanged("Level")
        End Sub
        
        Private Sub OnID_ScheduleChanged()
            Me.___OnPropertyChanged("ID_Schedule")
            Me.___OnPropertyChanged("Schedule")
        End Sub
        
        Private Property _ID_ClassImplementation() As Integer Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.ID_Class
            Get
                Return Me.ID_Class
            End Get
            Set(ByVal value As Integer)
                Me.ID_Class = value
            End Set
        End Property
        
        Private Sub OnID_ClassChanged()
            Me.___OnPropertyChanged("ID_Class")
        End Sub
        
        Private Property _Class_nameImplementation() As String Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.Class_name
            Get
                Return Me.Class_name
            End Get
            Set(ByVal value As String)
                Me.Class_name = value
            End Set
        End Property
        
        Private Sub OnClass_nameChanged()
            Me.___OnPropertyChanged("Class_name")
        End Sub
        
        Private Property _CapacityImplementation() As Global.System.Nullable(Of Integer) Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.Capacity
            Get
                Return Me.Capacity
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                Me.Capacity = value
            End Set
        End Property
        
        Private Sub OnCapacityChanged()
            Me.___OnPropertyChanged("Capacity")
        End Sub
        
        Private ReadOnly Property _ChildrenImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.Children
            Get
                Return Me.Children
            End Get
        End Property
        
        Friend ReadOnly Property __Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child) 
            Get
                If (Me.___Children Is Nothing) Then
                    Me.___Children = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)( _
                        Me, _
                        "Children", _
                        Function() Me._Children, _
                        Function(e) Global.System.Object.Equals(e.ID_Class, Me.ID_Class))
                End If
                Return Me.___Children
            End Get
        End Property
        
        Private ___Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)
        
        Private Property _LevelImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.Level
            Get
                Return Me.Level
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Level = DirectCast(value, Global.LightSwitchApplication.Implementation.Level)
            End Set
        End Property
        
        Private ReadOnly Property __Level As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Level) 
            Get
                If (Me.___Level Is Nothing) Then
                    Me.___Level = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Level)( _
                        Me, _
                        "Level", _
                        New Global.System.String() {"ID_Level"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Level, Me.ID_Level), _
                        Function() Me._Level, _
                        Sub(e) Me._Level = e)
                End If
                Return Me.___Level
            End Get
        End Property
        
        Private ___Level As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Level)
        
        Private Property _ScheduleImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Classroom.DetailsClass.IImplementation.Schedule
            Get
                Return Me.Schedule
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Schedule = DirectCast(value, Global.LightSwitchApplication.Implementation.Schedule)
            End Set
        End Property
        
        Private ReadOnly Property __Schedule As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule) 
            Get
                If (Me.___Schedule Is Nothing) Then
                    Me.___Schedule = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule)( _
                        Me, _
                        "Schedule", _
                        New Global.System.String() {"ID_Schedule"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Schedule, Me.ID_Schedule), _
                        Function() Me._Schedule, _
                        Sub(e) Me._Schedule = e)
                End If
                Return Me.___Schedule
            End Get
        End Property
        
        Private ___Schedule As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule)
        
    End Class
    #End Region
    
    #Region "Level"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Level
        Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation
        Private Property _ID_LevelImplementation() As Integer Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.ID_Level
            Get
                Return Me.ID_Level
            End Get
            Set(ByVal value As Integer)
                Me.ID_Level = value
            End Set
        End Property
        
        Private Sub OnID_LevelChanged()
            Me.___OnPropertyChanged("ID_Level")
        End Sub
        
        Private Property _Level_nameImplementation() As String Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.Level_name
            Get
                Return Me.Level_name
            End Get
            Set(ByVal value As String)
                Me.Level_name = value
            End Set
        End Property
        
        Private Sub OnLevel_nameChanged()
            Me.___OnPropertyChanged("Level_name")
        End Sub
        
        Private Property _FeesImplementation() As Integer Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.Fees
            Get
                Return Me.Fees
            End Get
            Set(ByVal value As Integer)
                Me.Fees = value
            End Set
        End Property
        
        Private Sub OnFeesChanged()
            Me.___OnPropertyChanged("Fees")
        End Sub
        
        Private Property _Age_fromImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.Age_from
            Get
                Return Me.Age_from
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.Age_from = value
            End Set
        End Property
        
        Private Sub OnAge_fromChanged()
            Me.___OnPropertyChanged("Age_from")
        End Sub
        
        Private Property _Age_toImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.Age_to
            Get
                Return Me.Age_to
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.Age_to = value
            End Set
        End Property
        
        Private Sub OnAge_toChanged()
            Me.___OnPropertyChanged("Age_to")
        End Sub
        
        Private ReadOnly Property _ClassroomsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Level.DetailsClass.IImplementation.Classrooms
            Get
                Return Me.Classrooms
            End Get
        End Property
        
        Friend ReadOnly Property __Classrooms As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom) 
            Get
                If (Me.___Classrooms Is Nothing) Then
                    Me.___Classrooms = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom)( _
                        Me, _
                        "Classrooms", _
                        Function() Me._Classrooms, _
                        Function(e) Global.System.Object.Equals(e.ID_Level, Me.ID_Level))
                End If
                Return Me.___Classrooms
            End Get
        End Property
        
        Private ___Classrooms As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom)
        
    End Class
    #End Region
    
    #Region "Parent"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Parent
        Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation
        Private Property _ID_ParentImplementation() As Integer Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation.ID_Parent
            Get
                Return Me.ID_Parent
            End Get
            Set(ByVal value As Integer)
                Me.ID_Parent = value
            End Set
        End Property
        
        Private Sub OnID_ParentChanged()
            Me.___OnPropertyChanged("ID_Parent")
        End Sub
        
        Private Property _NameImplementation() As String Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation.Name
            Get
                Return Me.Name
            End Get
            Set(ByVal value As String)
                Me.Name = value
            End Set
        End Property
        
        Private Sub OnNameChanged()
            Me.___OnPropertyChanged("Name")
        End Sub
        
        Private Property _AdressImplementation() As String Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation.Adress
            Get
                Return Me.Adress
            End Get
            Set(ByVal value As String)
                Me.Adress = value
            End Set
        End Property
        
        Private Sub OnAdressChanged()
            Me.___OnPropertyChanged("Adress")
        End Sub
        
        Private Property _PhoneImplementation() As Global.System.Nullable(Of Integer) Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation.Phone
            Get
                Return Me.Phone
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                Me.Phone = value
            End Set
        End Property
        
        Private Sub OnPhoneChanged()
            Me.___OnPropertyChanged("Phone")
        End Sub
        
        Private ReadOnly Property _ChildrenImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Parent.DetailsClass.IImplementation.Children
            Get
                Return Me.Children
            End Get
        End Property
        
        Friend ReadOnly Property __Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child) 
            Get
                If (Me.___Children Is Nothing) Then
                    Me.___Children = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)( _
                        Me, _
                        "Children", _
                        Function() Me._Children, _
                        Function(e) Global.System.Object.Equals(e.ID_Parent, Me.ID_Parent))
                End If
                Return Me.___Children
            End Get
        End Property
        
        Private ___Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)
        
    End Class
    #End Region
    
    #Region "Payment"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Payment
        Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation
        Private Property _ID_PayImplementation() As Integer Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.ID_Pay
            Get
                Return Me.ID_Pay
            End Get
            Set(ByVal value As Integer)
                Me.ID_Pay = value
            End Set
        End Property
        
        Private Sub OnID_PayChanged()
            Me.___OnPropertyChanged("ID_Pay")
        End Sub
        
        Private Property _ID_ChildImplementation() As Integer Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.ID_Child
            Get
                Return Me.ID_Child
            End Get
            Set(ByVal value As Integer)
                Me.ID_Child = value
            End Set
        End Property
        
        Private Sub OnID_ChildChanged()
            Me.___OnPropertyChanged("ID_Child")
        End Sub
        
        Private Property _c_DateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.c_Date
            Get
                Return Me.c_Date
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.c_Date = value
            End Set
        End Property
        
        Private Sub Onc_DateChanged()
            Me.___OnPropertyChanged("c_Date")
        End Sub
        
        Private Property _Total_FeesImplementation() As Global.System.Nullable(Of Integer) Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.Total_Fees
            Get
                Return Me.Total_Fees
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                Me.Total_Fees = value
            End Set
        End Property
        
        Private Sub OnTotal_FeesChanged()
            Me.___OnPropertyChanged("Total_Fees")
        End Sub
        
        Private Property _Payment1Implementation() As Global.System.Nullable(Of Integer) Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.Payment1
            Get
                Return Me.Payment1
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                Me.Payment1 = value
            End Set
        End Property
        
        Private Sub OnPayment1Changed()
            Me.___OnPropertyChanged("Payment1")
        End Sub
        
        Private ReadOnly Property _ChildrenImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Payment.DetailsClass.IImplementation.Children
            Get
                Return Me.Children
            End Get
        End Property
        
        Friend ReadOnly Property __Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child) 
            Get
                If (Me.___Children Is Nothing) Then
                    Me.___Children = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)( _
                        Me, _
                        "Children", _
                        Function() Me._Children, _
                        Function(e) Global.System.Object.Equals(e.ID_Pay, Me.ID_Pay))
                End If
                Return Me.___Children
            End Get
        End Property
        
        Private ___Children As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Child)
        
    End Class
    #End Region
    
    #Region "Schedule"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Schedule
        Implements Global.LightSwitchApplication.Schedule.DetailsClass.IImplementation
        Private Property _ID_ScheduleImplementation() As Integer Implements Global.LightSwitchApplication.Schedule.DetailsClass.IImplementation.ID_Schedule
            Get
                Return Me.ID_Schedule
            End Get
            Set(ByVal value As Integer)
                Me.ID_Schedule = value
            End Set
        End Property
        
        Private Sub OnID_ScheduleChanged()
            Me.___OnPropertyChanged("ID_Schedule")
        End Sub
        
        Private Property _NameImplementation() As Global.System.Nullable(Of Integer) Implements Global.LightSwitchApplication.Schedule.DetailsClass.IImplementation.Name
            Get
                Return Me.Name
            End Get
            Set(ByVal value As Global.System.Nullable(Of Integer))
                Me.Name = value
            End Set
        End Property
        
        Private Sub OnNameChanged()
            Me.___OnPropertyChanged("Name")
        End Sub
        
        Private ReadOnly Property _ClassroomsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Schedule.DetailsClass.IImplementation.Classrooms
            Get
                Return Me.Classrooms
            End Get
        End Property
        
        Friend ReadOnly Property __Classrooms As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom) 
            Get
                If (Me.___Classrooms Is Nothing) Then
                    Me.___Classrooms = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom)( _
                        Me, _
                        "Classrooms", _
                        Function() Me._Classrooms, _
                        Function(e) Global.System.Object.Equals(e.ID_Schedule, Me.ID_Schedule))
                End If
                Return Me.___Classrooms
            End Get
        End Property
        
        Private ___Classrooms As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Classroom)
        
        Private ReadOnly Property _Schedule_SessionsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Schedule.DetailsClass.IImplementation.Schedule_Sessions
            Get
                Return Me.Schedule_Sessions
            End Get
        End Property
        
        Friend ReadOnly Property __Schedule_Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session) 
            Get
                If (Me.___Schedule_Sessions Is Nothing) Then
                    Me.___Schedule_Sessions = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session)( _
                        Me, _
                        "Schedule_Sessions", _
                        Function() Me._Schedule_Sessions, _
                        Function(e) Global.System.Object.Equals(e.ID_Schedule, Me.ID_Schedule))
                End If
                Return Me.___Schedule_Sessions
            End Get
        End Property
        
        Private ___Schedule_Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session)
        
    End Class
    #End Region
    
    #Region "Schedule_Session"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Schedule_Session
        Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation
        Private Property _ID_ScheduleImplementation() As Integer Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation.ID_Schedule
            Get
                Return Me.ID_Schedule
            End Get
            Set(ByVal value As Integer)
                Me.ID_Schedule = value
            End Set
        End Property
        
        Private Sub OnID_ScheduleChanged()
            Me.___OnPropertyChanged("ID_Schedule")
            Me.___OnPropertyChanged("Schedule")
        End Sub
        
        Private Property _ID_SessionImplementation() As Integer Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation.ID_Session
            Get
                Return Me.ID_Session
            End Get
            Set(ByVal value As Integer)
                Me.ID_Session = value
            End Set
        End Property
        
        Private Sub OnID_SessionChanged()
            Me.___OnPropertyChanged("ID_Session")
            Me.___OnPropertyChanged("Session")
        End Sub
        
        Private Property _DayImplementation() As String Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation.Day
            Get
                Return Me.Day
            End Get
            Set(ByVal value As String)
                Me.Day = value
            End Set
        End Property
        
        Private Sub OnDayChanged()
            Me.___OnPropertyChanged("Day")
        End Sub
        
        Private Property _ScheduleImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation.Schedule
            Get
                Return Me.Schedule
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Schedule = DirectCast(value, Global.LightSwitchApplication.Implementation.Schedule)
            End Set
        End Property
        
        Private ReadOnly Property __Schedule As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule) 
            Get
                If (Me.___Schedule Is Nothing) Then
                    Me.___Schedule = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule)( _
                        Me, _
                        "Schedule", _
                        New Global.System.String() {"ID_Schedule"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Schedule, Me.ID_Schedule), _
                        Function() Me._Schedule, _
                        Sub(e) Me._Schedule = e)
                End If
                Return Me.___Schedule
            End Get
        End Property
        
        Private ___Schedule As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Schedule)
        
        Private Property _SessionImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Schedule_Session.DetailsClass.IImplementation.Session
            Get
                Return Me.Session
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Session = DirectCast(value, Global.LightSwitchApplication.Implementation.Session)
            End Set
        End Property
        
        Private ReadOnly Property __Session As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Session) 
            Get
                If (Me.___Session Is Nothing) Then
                    Me.___Session = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Session)( _
                        Me, _
                        "Session", _
                        New Global.System.String() {"ID_Session"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Session, Me.ID_Session), _
                        Function() Me._Session, _
                        Sub(e) Me._Session = e)
                End If
                Return Me.___Session
            End Get
        End Property
        
        Private ___Session As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Session)
        
    End Class
    #End Region
    
    #Region "Session"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Session
        Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation
        Private Sub OnID_TeacherChanged()
            Me.___OnPropertyChanged("ID_Teacher")
            Me.___OnPropertyChanged("Teacher")
        End Sub
        
        Private Property _ID_SessionImplementation() As Integer Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.ID_Session
            Get
                Return Me.ID_Session
            End Get
            Set(ByVal value As Integer)
                Me.ID_Session = value
            End Set
        End Property
        
        Private Sub OnID_SessionChanged()
            Me.___OnPropertyChanged("ID_Session")
        End Sub
        
        Private Property _Time_StartImplementation() As Global.System.TimeSpan Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.Time_Start
            Get
                Return Me.Time_Start
            End Get
            Set(ByVal value As Global.System.TimeSpan)
                Me.Time_Start = value
            End Set
        End Property
        
        Private Sub OnTime_StartChanged()
            Me.___OnPropertyChanged("Time_Start")
        End Sub
        
        Private Property _Time_EndImplementation() As Global.System.TimeSpan Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.Time_End
            Get
                Return Me.Time_End
            End Get
            Set(ByVal value As Global.System.TimeSpan)
                Me.Time_End = value
            End Set
        End Property
        
        Private Sub OnTime_EndChanged()
            Me.___OnPropertyChanged("Time_End")
        End Sub
        
        Private Property _NameImplementation() As String Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.Name
            Get
                Return Me.Name
            End Get
            Set(ByVal value As String)
                Me.Name = value
            End Set
        End Property
        
        Private Sub OnNameChanged()
            Me.___OnPropertyChanged("Name")
        End Sub
        
        Private ReadOnly Property _Schedule_SessionsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.Schedule_Sessions
            Get
                Return Me.Schedule_Sessions
            End Get
        End Property
        
        Friend ReadOnly Property __Schedule_Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session) 
            Get
                If (Me.___Schedule_Sessions Is Nothing) Then
                    Me.___Schedule_Sessions = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session)( _
                        Me, _
                        "Schedule_Sessions", _
                        Function() Me._Schedule_Sessions, _
                        Function(e) Global.System.Object.Equals(e.ID_Session, Me.ID_Session))
                End If
                Return Me.___Schedule_Sessions
            End Get
        End Property
        
        Private ___Schedule_Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Schedule_Session)
        
        Private Property _TeacherImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Session.DetailsClass.IImplementation.Teacher
            Get
                Return Me.Teacher
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Teacher = DirectCast(value, Global.LightSwitchApplication.Implementation.Teacher)
            End Set
        End Property
        
        Private ReadOnly Property __Teacher As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Teacher) 
            Get
                If (Me.___Teacher Is Nothing) Then
                    Me.___Teacher = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Teacher)( _
                        Me, _
                        "Teacher", _
                        New Global.System.String() {"ID_Teacher"}, _
                        Function(e) Global.System.Object.Equals(e.ID_Teacher, Me.ID_Teacher), _
                        Function() Me._Teacher, _
                        Sub(e) Me._Teacher = e)
                End If
                Return Me.___Teacher
            End Get
        End Property
        
        Private ___Teacher As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef(Of Global.LightSwitchApplication.Implementation.Teacher)
        
    End Class
    #End Region
    
    #Region "Teacher"
    <Global.System.Runtime.Serialization.DataContract(Namespace:="http://schemas.datacontract.org/2004/07/IS_projectData.Implementation")> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class Teacher
        Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation
        Private Property _ID_TeacherImplementation() As Integer Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation.ID_Teacher
            Get
                Return Me.ID_Teacher
            End Get
            Set(ByVal value As Integer)
                Me.ID_Teacher = value
            End Set
        End Property
        
        Private Sub OnID_TeacherChanged()
            Me.___OnPropertyChanged("ID_Teacher")
        End Sub
        
        Private Property _NameImplementation() As String Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation.Name
            Get
                Return Me.Name
            End Get
            Set(ByVal value As String)
                Me.Name = value
            End Set
        End Property
        
        Private Sub OnNameChanged()
            Me.___OnPropertyChanged("Name")
        End Sub
        
        Private Property _Phone_noImplementation() As Integer Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation.Phone_no
            Get
                Return Me.Phone_no
            End Get
            Set(ByVal value As Integer)
                Me.Phone_no = value
            End Set
        End Property
        
        Private Sub OnPhone_noChanged()
            Me.___OnPropertyChanged("Phone_no")
        End Sub
        
        Private Property _salaryImplementation() As Integer Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation.salary
            Get
                Return Me.salary
            End Get
            Set(ByVal value As Integer)
                Me.salary = value
            End Set
        End Property
        
        Private Sub OnsalaryChanged()
            Me.___OnPropertyChanged("salary")
        End Sub
        
        Private ReadOnly Property _SessionsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Teacher.DetailsClass.IImplementation.Sessions
            Get
                Return Me.Sessions
            End Get
        End Property
        
        Friend ReadOnly Property __Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Session) 
            Get
                If (Me.___Sessions Is Nothing) Then
                    Me.___Sessions = New Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Session)( _
                        Me, _
                        "Sessions", _
                        Function() Me._Sessions, _
                        Function(e) Global.System.Object.Equals(e.ID_Teacher, Me.ID_Teacher))
                End If
                Return Me.___Sessions
            End Get
        End Property
        
        Private ___Sessions As Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection(Of Global.LightSwitchApplication.Implementation.Session)
        
    End Class
    #End Region
    
    #Region "IS_projectDataObjectContext"
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Partial Class IS_projectDataObjectContext
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Child)) Then
                Return New Global.LightSwitchApplication.Implementation.Child()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Classroom)) Then
                Return New Global.LightSwitchApplication.Implementation.Classroom()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Level)) Then
                Return New Global.LightSwitchApplication.Implementation.Level()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Parent)) Then
                Return New Global.LightSwitchApplication.Implementation.Parent()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Payment)) Then
                Return New Global.LightSwitchApplication.Implementation.Payment()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Schedule)) Then
                Return New Global.LightSwitchApplication.Implementation.Schedule()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Schedule_Session)) Then
                Return New Global.LightSwitchApplication.Implementation.Schedule_Session()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Session)) Then
                Return New Global.LightSwitchApplication.Implementation.Session()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Teacher)) Then
                Return New Global.LightSwitchApplication.Implementation.Teacher()
            End If
            Return Nothing
        End Function
    End Class
    #End Region
    
    #Region "DataServiceImplementationFactory"
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.IDataServiceFactory))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class DataServiceFactory
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    
        Protected Overrides Function CreateDataService(ByVal dataServiceType As Global.System.Type) As Global.Microsoft.LightSwitch.IDataService
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.IS_projectData)) Then
                Return New Global.LightSwitchApplication.IS_projectData()
            End If
            Return MyBase.CreateDataService(dataServiceType)
        End Function
    
        Protected Overrides Function CreateDataServiceImplementation(Of TDataService As Global.Microsoft.LightSwitch.IDataService)(ByVal dataService As TDataService) As Global.Microsoft.LightSwitch.Internal.IDataServiceImplementation
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.IS_projectData)) Then
                Return New Global.LightSwitchApplication.Implementation.IS_projectDataObjectContext(Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../IS_projectData.svc"))
            End If
            Return MyBase.CreateDataServiceImplementation(dataService)
        End Function
    End Class
    #End Region
    
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __TypeMapping
        Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider
        Private Function GetImplementationType(ByVal definitionType As Global.System.Type) As Global.System.Type Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType
            If GetType(Global.LightSwitchApplication.Child).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Child)
            End If
            If GetType(Global.LightSwitchApplication.Classroom).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Classroom)
            End If
            If GetType(Global.LightSwitchApplication.Level).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Level)
            End If
            If GetType(Global.LightSwitchApplication.Parent).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Parent)
            End If
            If GetType(Global.LightSwitchApplication.Payment).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Payment)
            End If
            If GetType(Global.LightSwitchApplication.Schedule).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Schedule)
            End If
            If GetType(Global.LightSwitchApplication.Schedule_Session).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Schedule_Session)
            End If
            If GetType(Global.LightSwitchApplication.Session).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Session)
            End If
            If GetType(Global.LightSwitchApplication.Teacher).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Teacher)
            End If
            Return Nothing
        End Function
    End Class
End Namespace
