'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 12/17/2012 10:44:52 AM
Namespace LightSwitchApplication.Implementation
    '''<summary>
    '''There are no comments for IS_projectDataObjectContext in the schema.
    '''</summary>
    Partial Public Class IS_projectDataObjectContext
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
        '''<summary>
        '''Initialize a new IS_projectDataObjectContext object.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(LightSwitchApplication.Implementation.IS_projectDataObjectContext).Namespace.Remove(GetType(LightSwitchApplication.Implementation.IS_projectDataObjectContext).Namespace.LastIndexOf("LightSwitchApplication.Implementation"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("LightSwitchApplication", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "LightSwitchApplication.Implementation"), typeName.Substring(22)), false)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "LightSwitchApplication.Implementation"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("LightSwitchApplication.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Children in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Children() As Global.System.Data.Services.Client.DataServiceQuery(Of Child)
            Get
                If (Me._Children Is Nothing) Then
                    Me._Children = MyBase.CreateQuery(Of Child)("Children")
                End If
                Return Me._Children
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Children As Global.System.Data.Services.Client.DataServiceQuery(Of Child)
        '''<summary>
        '''There are no comments for Classrooms in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Classrooms() As Global.System.Data.Services.Client.DataServiceQuery(Of Classroom)
            Get
                If (Me._Classrooms Is Nothing) Then
                    Me._Classrooms = MyBase.CreateQuery(Of Classroom)("Classrooms")
                End If
                Return Me._Classrooms
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Classrooms As Global.System.Data.Services.Client.DataServiceQuery(Of Classroom)
        '''<summary>
        '''There are no comments for Levels in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Levels() As Global.System.Data.Services.Client.DataServiceQuery(Of Level)
            Get
                If (Me._Levels Is Nothing) Then
                    Me._Levels = MyBase.CreateQuery(Of Level)("Levels")
                End If
                Return Me._Levels
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Levels As Global.System.Data.Services.Client.DataServiceQuery(Of Level)
        '''<summary>
        '''There are no comments for Parents in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Parents() As Global.System.Data.Services.Client.DataServiceQuery(Of Parent)
            Get
                If (Me._Parents Is Nothing) Then
                    Me._Parents = MyBase.CreateQuery(Of Parent)("Parents")
                End If
                Return Me._Parents
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Parents As Global.System.Data.Services.Client.DataServiceQuery(Of Parent)
        '''<summary>
        '''There are no comments for Payments in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Payments() As Global.System.Data.Services.Client.DataServiceQuery(Of Payment)
            Get
                If (Me._Payments Is Nothing) Then
                    Me._Payments = MyBase.CreateQuery(Of Payment)("Payments")
                End If
                Return Me._Payments
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Payments As Global.System.Data.Services.Client.DataServiceQuery(Of Payment)
        '''<summary>
        '''There are no comments for Schedules in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Schedules() As Global.System.Data.Services.Client.DataServiceQuery(Of Schedule)
            Get
                If (Me._Schedules Is Nothing) Then
                    Me._Schedules = MyBase.CreateQuery(Of Schedule)("Schedules")
                End If
                Return Me._Schedules
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedules As Global.System.Data.Services.Client.DataServiceQuery(Of Schedule)
        '''<summary>
        '''There are no comments for Schedule_Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Schedule_Sessions() As Global.System.Data.Services.Client.DataServiceQuery(Of Schedule_Session)
            Get
                If (Me._Schedule_Sessions Is Nothing) Then
                    Me._Schedule_Sessions = MyBase.CreateQuery(Of Schedule_Session)("Schedule_Sessions")
                End If
                Return Me._Schedule_Sessions
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedule_Sessions As Global.System.Data.Services.Client.DataServiceQuery(Of Schedule_Session)
        '''<summary>
        '''There are no comments for Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Sessions() As Global.System.Data.Services.Client.DataServiceQuery(Of Session)
            Get
                If (Me._Sessions Is Nothing) Then
                    Me._Sessions = MyBase.CreateQuery(Of Session)("Sessions")
                End If
                Return Me._Sessions
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Sessions As Global.System.Data.Services.Client.DataServiceQuery(Of Session)
        '''<summary>
        '''There are no comments for Teachers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Teachers() As Global.System.Data.Services.Client.DataServiceQuery(Of Teacher)
            Get
                If (Me._Teachers Is Nothing) Then
                    Me._Teachers = MyBase.CreateQuery(Of Teacher)("Teachers")
                End If
                Return Me._Teachers
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Teachers As Global.System.Data.Services.Client.DataServiceQuery(Of Teacher)
        '''<summary>
        '''There are no comments for Children in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToChildren(ByVal child As Child)
            MyBase.AddObject("Children", child)
        End Sub
        '''<summary>
        '''There are no comments for Classrooms in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToClassrooms(ByVal classroom As Classroom)
            MyBase.AddObject("Classrooms", classroom)
        End Sub
        '''<summary>
        '''There are no comments for Levels in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToLevels(ByVal level As Level)
            MyBase.AddObject("Levels", level)
        End Sub
        '''<summary>
        '''There are no comments for Parents in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToParents(ByVal parent As Parent)
            MyBase.AddObject("Parents", parent)
        End Sub
        '''<summary>
        '''There are no comments for Payments in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToPayments(ByVal payment As Payment)
            MyBase.AddObject("Payments", payment)
        End Sub
        '''<summary>
        '''There are no comments for Schedules in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSchedules(ByVal schedule As Schedule)
            MyBase.AddObject("Schedules", schedule)
        End Sub
        '''<summary>
        '''There are no comments for Schedule_Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSchedule_Sessions(ByVal schedule_Session As Schedule_Session)
            MyBase.AddObject("Schedule_Sessions", schedule_Session)
        End Sub
        '''<summary>
        '''There are no comments for Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToSessions(ByVal session As Session)
            MyBase.AddObject("Sessions", session)
        End Sub
        '''<summary>
        '''There are no comments for Teachers in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToTeachers(ByVal teacher As Teacher)
            MyBase.AddObject("Teachers", teacher)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Child in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Child
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Children"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Child")>  _
    Partial Public Class Child
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Child object.
        '''</summary>
        '''<param name="iD_Child">Initial value of ID_Child.</param>
        '''<param name="name">Initial value of Name.</param>
        '''<param name="birth_date">Initial value of Birth_date.</param>
        '''<param name="gender">Initial value of Gender.</param>
        '''<param name="iD_Class">Initial value of ID_Class.</param>
        '''<param name="iD_Parent">Initial value of ID_Parent.</param>
        '''<param name="iD_Pay">Initial value of ID_Pay.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateChild(ByVal iD_Child As Integer, ByVal name As String, ByVal birth_date As Date, ByVal gender As String, ByVal iD_Class As Integer, ByVal iD_Parent As Integer, ByVal iD_Pay As Integer) As Child
            Dim child As Child = New Child()
            child.ID_Child = iD_Child
            child.Name = name
            child.Birth_date = birth_date
            child.Gender = gender
            child.ID_Class = iD_Class
            child.ID_Parent = iD_Parent
            child.ID_Pay = iD_Pay
            Return child
        End Function
        '''<summary>
        '''There are no comments for Property ID_Child in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Child() As Integer
            Get
                Return Me._ID_Child
            End Get
            Set
                Me.OnID_ChildChanging(value)
                If Object.Equals(Me.ID_Child, value) Then
                    Return
                End If
                Me._ID_Child = value
                Me.OnID_ChildChanged
                Me.OnPropertyChanged("ID_Child")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Child As Integer
        Partial Private Sub OnID_ChildChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ChildChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                If Object.Equals(Me.Name, value) Then
                    Return
                End If
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Birth_date in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Birth_date() As Date
            Get
                Return Me._Birth_date
            End Get
            Set
                Me.OnBirth_dateChanging(value)
                If Object.Equals(Me.Birth_date, value) Then
                    Return
                End If
                Me._Birth_date = value
                Me.OnBirth_dateChanged
                Me.OnPropertyChanged("Birth_date")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Birth_date As Date
        Partial Private Sub OnBirth_dateChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnBirth_dateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Gender in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Gender() As String
            Get
                Return Me._Gender
            End Get
            Set
                Me.OnGenderChanging(value)
                If Object.Equals(Me.Gender, value) Then
                    Return
                End If
                Me._Gender = value
                Me.OnGenderChanged
                Me.OnPropertyChanged("Gender")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Gender As String
        Partial Private Sub OnGenderChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnGenderChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Class in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Class() As Integer
            Get
                Return Me._ID_Class
            End Get
            Set
                Me.OnID_ClassChanging(value)
                If Object.Equals(Me.ID_Class, value) Then
                    Return
                End If
                Me._ID_Class = value
                Me.OnID_ClassChanged
                Me.OnPropertyChanged("ID_Class")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Class As Integer
        Partial Private Sub OnID_ClassChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ClassChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Parent in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Parent() As Integer
            Get
                Return Me._ID_Parent
            End Get
            Set
                Me.OnID_ParentChanging(value)
                If Object.Equals(Me.ID_Parent, value) Then
                    Return
                End If
                Me._ID_Parent = value
                Me.OnID_ParentChanged
                Me.OnPropertyChanged("ID_Parent")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Parent As Integer
        Partial Private Sub OnID_ParentChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ParentChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Pay in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Pay() As Integer
            Get
                Return Me._ID_Pay
            End Get
            Set
                Me.OnID_PayChanging(value)
                If Object.Equals(Me.ID_Pay, value) Then
                    Return
                End If
                Me._ID_Pay = value
                Me.OnID_PayChanged
                Me.OnPropertyChanged("ID_Pay")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Pay As Integer
        Partial Private Sub OnID_PayChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_PayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Classroom in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Classroom() As Classroom
            Get
                Me.__Classroom.EnsureValueInitialized
                Return Me._Classroom
            End Get
            Set
                Dim previous As Classroom = Me.Classroom
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Classroom = Nothing
                    Me.__Classroom.OnValueSet
                    previous.Children.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Class = value.ID_Class
                    Else
                        Me.ID_Class = CType(Nothing, Integer)
                    End If
                End If
                Me._Classroom = value
                Me.__Classroom.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Children.Add(Me)
                End If
                Me.___OnPropertyChanged("Classroom")
                Me.OnPropertyChanged("Classroom")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Classroom As Classroom
        '''<summary>
        '''There are no comments for Parent in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Parent() As Parent
            Get
                Me.__Parent.EnsureValueInitialized
                Return Me._Parent
            End Get
            Set
                Dim previous As Parent = Me.Parent
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Parent = Nothing
                    Me.__Parent.OnValueSet
                    previous.Children.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Parent = value.ID_Parent
                    Else
                        Me.ID_Parent = CType(Nothing, Integer)
                    End If
                End If
                Me._Parent = value
                Me.__Parent.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Children.Add(Me)
                End If
                Me.___OnPropertyChanged("Parent")
                Me.OnPropertyChanged("Parent")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Parent As Parent
        '''<summary>
        '''There are no comments for Payment in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Payment() As Payment
            Get
                Me.__Payment.EnsureValueInitialized
                Return Me._Payment
            End Get
            Set
                Dim previous As Payment = Me.Payment
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Payment = Nothing
                    Me.__Payment.OnValueSet
                    previous.Children.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Pay = value.ID_Pay
                    Else
                        Me.ID_Pay = CType(Nothing, Integer)
                    End If
                End If
                Me._Payment = value
                Me.__Payment.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Children.Add(Me)
                End If
                Me.___OnPropertyChanged("Payment")
                Me.OnPropertyChanged("Payment")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Payment As Payment
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Classroom in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Class
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Classrooms"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Class")>  _
    Partial Public Class Classroom
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Classroom object.
        '''</summary>
        '''<param name="iD_Class">Initial value of ID_Class.</param>
        '''<param name="class_name">Initial value of Class_name.</param>
        '''<param name="iD_Level">Initial value of ID_Level.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateClassroom(ByVal iD_Class As Integer, ByVal class_name As String, ByVal iD_Level As Integer) As Classroom
            Dim classroom As Classroom = New Classroom()
            classroom.ID_Class = iD_Class
            classroom.Class_name = class_name
            classroom.ID_Level = iD_Level
            Return classroom
        End Function
        '''<summary>
        '''There are no comments for Property ID_Class in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Class() As Integer
            Get
                Return Me._ID_Class
            End Get
            Set
                Me.OnID_ClassChanging(value)
                If Object.Equals(Me.ID_Class, value) Then
                    Return
                End If
                Me._ID_Class = value
                Me.OnID_ClassChanged
                Me.OnPropertyChanged("ID_Class")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Class As Integer
        Partial Private Sub OnID_ClassChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ClassChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Class_name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Class_name() As String
            Get
                Return Me._Class_name
            End Get
            Set
                Me.OnClass_nameChanging(value)
                If Object.Equals(Me.Class_name, value) Then
                    Return
                End If
                Me._Class_name = value
                Me.OnClass_nameChanged
                Me.OnPropertyChanged("Class_name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Class_name As String
        Partial Private Sub OnClass_nameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnClass_nameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Capacity in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Capacity() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Capacity
            End Get
            Set
                Me.OnCapacityChanging(value)
                If Object.Equals(Me.Capacity, value) Then
                    Return
                End If
                Me._Capacity = value
                Me.OnCapacityChanged
                Me.OnPropertyChanged("Capacity")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Capacity As Global.System.Nullable(Of Integer)
        Partial Private Sub OnCapacityChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnCapacityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Level in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Level() As Integer
            Get
                Return Me._ID_Level
            End Get
            Set
                Me.OnID_LevelChanging(value)
                If Object.Equals(Me.ID_Level, value) Then
                    Return
                End If
                Me._ID_Level = value
                Me.OnID_LevelChanged
                Me.OnPropertyChanged("ID_Level")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Level As Integer
        Partial Private Sub OnID_LevelChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_LevelChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Schedule in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Schedule() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ID_Schedule
            End Get
            Set
                Me.OnID_ScheduleChanging(value)
                If Object.Equals(Me.ID_Schedule, value) Then
                    Return
                End If
                Me._ID_Schedule = value
                Me.OnID_ScheduleChanged
                Me.OnPropertyChanged("ID_Schedule")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Schedule As Global.System.Nullable(Of Integer)
        Partial Private Sub OnID_ScheduleChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnID_ScheduleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Children in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Children() As Global.System.Data.Services.Client.DataServiceCollection(Of Child)
            Get
                Me.__Children.EnsureValueInitialized
                Return Me._Children
            End Get
            Set
                Me._Children = value
                Me.OnPropertyChanged("Children")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Children As Global.System.Data.Services.Client.DataServiceCollection(Of Child) = New Global.System.Data.Services.Client.DataServiceCollection(Of Child)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Level in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Level() As Level
            Get
                Me.__Level.EnsureValueInitialized
                Return Me._Level
            End Get
            Set
                Dim previous As Level = Me.Level
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Level = Nothing
                    Me.__Level.OnValueSet
                    previous.Classrooms.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Level = value.ID_Level
                    Else
                        Me.ID_Level = CType(Nothing, Integer)
                    End If
                End If
                Me._Level = value
                Me.__Level.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Classrooms.Add(Me)
                End If
                Me.___OnPropertyChanged("Level")
                Me.OnPropertyChanged("Level")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Level As Level
        '''<summary>
        '''There are no comments for Schedule in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Schedule() As Schedule
            Get
                Me.__Schedule.EnsureValueInitialized
                Return Me._Schedule
            End Get
            Set
                Dim previous As Schedule = Me.Schedule
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Schedule = Nothing
                    Me.__Schedule.OnValueSet
                    previous.Classrooms.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Schedule = value.ID_Schedule
                    Else
                        Me.ID_Schedule = CType(Nothing, Global.System.Nullable(Of Integer))
                    End If
                End If
                Me._Schedule = value
                Me.__Schedule.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Classrooms.Add(Me)
                End If
                Me.___OnPropertyChanged("Schedule")
                Me.OnPropertyChanged("Schedule")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedule As Schedule
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Level in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Level
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Levels"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Level")>  _
    Partial Public Class Level
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Level object.
        '''</summary>
        '''<param name="iD_Level">Initial value of ID_Level.</param>
        '''<param name="level_name">Initial value of Level_name.</param>
        '''<param name="fees">Initial value of Fees.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateLevel(ByVal iD_Level As Integer, ByVal level_name As String, ByVal fees As Integer) As Level
            Dim level As Level = New Level()
            level.ID_Level = iD_Level
            level.Level_name = level_name
            level.Fees = fees
            Return level
        End Function
        '''<summary>
        '''There are no comments for Property ID_Level in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Level() As Integer
            Get
                Return Me._ID_Level
            End Get
            Set
                Me.OnID_LevelChanging(value)
                If Object.Equals(Me.ID_Level, value) Then
                    Return
                End If
                Me._ID_Level = value
                Me.OnID_LevelChanged
                Me.OnPropertyChanged("ID_Level")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Level As Integer
        Partial Private Sub OnID_LevelChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_LevelChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Level_name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Level_name() As String
            Get
                Return Me._Level_name
            End Get
            Set
                Me.OnLevel_nameChanging(value)
                If Object.Equals(Me.Level_name, value) Then
                    Return
                End If
                Me._Level_name = value
                Me.OnLevel_nameChanged
                Me.OnPropertyChanged("Level_name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Level_name As String
        Partial Private Sub OnLevel_nameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnLevel_nameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Fees in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Fees() As Integer
            Get
                Return Me._Fees
            End Get
            Set
                Me.OnFeesChanging(value)
                If Object.Equals(Me.Fees, value) Then
                    Return
                End If
                Me._Fees = value
                Me.OnFeesChanged
                Me.OnPropertyChanged("Fees")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Fees As Integer
        Partial Private Sub OnFeesChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnFeesChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Age_from in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Age_from() As Global.System.Nullable(Of Date)
            Get
                Return Me._Age_from
            End Get
            Set
                Me.OnAge_fromChanging(value)
                If Object.Equals(Me.Age_from, value) Then
                    Return
                End If
                Me._Age_from = value
                Me.OnAge_fromChanged
                Me.OnPropertyChanged("Age_from")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Age_from As Global.System.Nullable(Of Date)
        Partial Private Sub OnAge_fromChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAge_fromChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Age_to in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Age_to() As Global.System.Nullable(Of Date)
            Get
                Return Me._Age_to
            End Get
            Set
                Me.OnAge_toChanging(value)
                If Object.Equals(Me.Age_to, value) Then
                    Return
                End If
                Me._Age_to = value
                Me.OnAge_toChanged
                Me.OnPropertyChanged("Age_to")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Age_to As Global.System.Nullable(Of Date)
        Partial Private Sub OnAge_toChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnAge_toChanged()
        End Sub
        '''<summary>
        '''There are no comments for Classrooms in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Classrooms() As Global.System.Data.Services.Client.DataServiceCollection(Of Classroom)
            Get
                Me.__Classrooms.EnsureValueInitialized
                Return Me._Classrooms
            End Get
            Set
                Me._Classrooms = value
                Me.OnPropertyChanged("Classrooms")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Classrooms As Global.System.Data.Services.Client.DataServiceCollection(Of Classroom) = New Global.System.Data.Services.Client.DataServiceCollection(Of Classroom)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Parent in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Parent
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Parents"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Parent")>  _
    Partial Public Class Parent
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Parent object.
        '''</summary>
        '''<param name="iD_Parent">Initial value of ID_Parent.</param>
        '''<param name="name">Initial value of Name.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateParent(ByVal iD_Parent As Integer, ByVal name As String) As Parent
            Dim parent As Parent = New Parent()
            parent.ID_Parent = iD_Parent
            parent.Name = name
            Return parent
        End Function
        '''<summary>
        '''There are no comments for Property ID_Parent in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Parent() As Integer
            Get
                Return Me._ID_Parent
            End Get
            Set
                Me.OnID_ParentChanging(value)
                If Object.Equals(Me.ID_Parent, value) Then
                    Return
                End If
                Me._ID_Parent = value
                Me.OnID_ParentChanged
                Me.OnPropertyChanged("ID_Parent")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Parent As Integer
        Partial Private Sub OnID_ParentChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ParentChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                If Object.Equals(Me.Name, value) Then
                    Return
                End If
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Adress in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Adress() As String
            Get
                Return Me._Adress
            End Get
            Set
                Me.OnAdressChanging(value)
                If Object.Equals(Me.Adress, value) Then
                    Return
                End If
                Me._Adress = value
                Me.OnAdressChanged
                Me.OnPropertyChanged("Adress")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Adress As String
        Partial Private Sub OnAdressChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAdressChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Phone in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Phone() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Phone
            End Get
            Set
                Me.OnPhoneChanging(value)
                If Object.Equals(Me.Phone, value) Then
                    Return
                End If
                Me._Phone = value
                Me.OnPhoneChanged
                Me.OnPropertyChanged("Phone")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Phone As Global.System.Nullable(Of Integer)
        Partial Private Sub OnPhoneChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnPhoneChanged()
        End Sub
        '''<summary>
        '''There are no comments for Children in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Children() As Global.System.Data.Services.Client.DataServiceCollection(Of Child)
            Get
                Me.__Children.EnsureValueInitialized
                Return Me._Children
            End Get
            Set
                Me._Children = value
                Me.OnPropertyChanged("Children")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Children As Global.System.Data.Services.Client.DataServiceCollection(Of Child) = New Global.System.Data.Services.Client.DataServiceCollection(Of Child)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Payment in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Pay
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Payments"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Pay")>  _
    Partial Public Class Payment
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Payment object.
        '''</summary>
        '''<param name="iD_Pay">Initial value of ID_Pay.</param>
        '''<param name="iD_Child">Initial value of ID_Child.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreatePayment(ByVal iD_Pay As Integer, ByVal iD_Child As Integer) As Payment
            Dim payment As Payment = New Payment()
            payment.ID_Pay = iD_Pay
            payment.ID_Child = iD_Child
            Return payment
        End Function
        '''<summary>
        '''There are no comments for Property ID_Pay in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Pay() As Integer
            Get
                Return Me._ID_Pay
            End Get
            Set
                Me.OnID_PayChanging(value)
                If Object.Equals(Me.ID_Pay, value) Then
                    Return
                End If
                Me._ID_Pay = value
                Me.OnID_PayChanged
                Me.OnPropertyChanged("ID_Pay")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Pay As Integer
        Partial Private Sub OnID_PayChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_PayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Child in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Child() As Integer
            Get
                Return Me._ID_Child
            End Get
            Set
                Me.OnID_ChildChanging(value)
                If Object.Equals(Me.ID_Child, value) Then
                    Return
                End If
                Me._ID_Child = value
                Me.OnID_ChildChanged
                Me.OnPropertyChanged("ID_Child")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Child As Integer
        Partial Private Sub OnID_ChildChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ChildChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property c_Date in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property c_Date() As Global.System.Nullable(Of Date)
            Get
                Return Me._c_Date
            End Get
            Set
                Me.Onc_DateChanging(value)
                If Object.Equals(Me.c_Date, value) Then
                    Return
                End If
                Me._c_Date = value
                Me.Onc_DateChanged
                Me.OnPropertyChanged("c_Date")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _c_Date As Global.System.Nullable(Of Date)
        Partial Private Sub Onc_DateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub Onc_DateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Total_Fees in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Total_Fees() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Total_Fees
            End Get
            Set
                Me.OnTotal_FeesChanging(value)
                If Object.Equals(Me.Total_Fees, value) Then
                    Return
                End If
                Me._Total_Fees = value
                Me.OnTotal_FeesChanged
                Me.OnPropertyChanged("Total_Fees")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Total_Fees As Global.System.Nullable(Of Integer)
        Partial Private Sub OnTotal_FeesChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnTotal_FeesChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Payment1 in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Payment1() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Payment1
            End Get
            Set
                Me.OnPayment1Changing(value)
                If Object.Equals(Me.Payment1, value) Then
                    Return
                End If
                Me._Payment1 = value
                Me.OnPayment1Changed
                Me.OnPropertyChanged("Payment1")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Payment1 As Global.System.Nullable(Of Integer)
        Partial Private Sub OnPayment1Changing(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnPayment1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Children in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Children() As Global.System.Data.Services.Client.DataServiceCollection(Of Child)
            Get
                Me.__Children.EnsureValueInitialized
                Return Me._Children
            End Get
            Set
                Me._Children = value
                Me.OnPropertyChanged("Children")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Children As Global.System.Data.Services.Client.DataServiceCollection(Of Child) = New Global.System.Data.Services.Client.DataServiceCollection(Of Child)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Schedule in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Schedule
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Schedules"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Schedule")>  _
    Partial Public Class Schedule
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Schedule object.
        '''</summary>
        '''<param name="iD_Schedule">Initial value of ID_Schedule.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSchedule(ByVal iD_Schedule As Integer) As Schedule
            Dim schedule As Schedule = New Schedule()
            schedule.ID_Schedule = iD_Schedule
            Return schedule
        End Function
        '''<summary>
        '''There are no comments for Property ID_Schedule in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Schedule() As Integer
            Get
                Return Me._ID_Schedule
            End Get
            Set
                Me.OnID_ScheduleChanging(value)
                If Object.Equals(Me.ID_Schedule, value) Then
                    Return
                End If
                Me._ID_Schedule = value
                Me.OnID_ScheduleChanged
                Me.OnPropertyChanged("ID_Schedule")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Schedule As Integer
        Partial Private Sub OnID_ScheduleChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ScheduleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As Global.System.Nullable(Of Integer)
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                If Object.Equals(Me.Name, value) Then
                    Return
                End If
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As Global.System.Nullable(Of Integer)
        Partial Private Sub OnNameChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Classrooms in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Classrooms() As Global.System.Data.Services.Client.DataServiceCollection(Of Classroom)
            Get
                Me.__Classrooms.EnsureValueInitialized
                Return Me._Classrooms
            End Get
            Set
                Me._Classrooms = value
                Me.OnPropertyChanged("Classrooms")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Classrooms As Global.System.Data.Services.Client.DataServiceCollection(Of Classroom) = New Global.System.Data.Services.Client.DataServiceCollection(Of Classroom)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Schedule_Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Schedule_Sessions() As Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session)
            Get
                Me.__Schedule_Sessions.EnsureValueInitialized
                Return Me._Schedule_Sessions
            End Get
            Set
                Me._Schedule_Sessions = value
                Me.OnPropertyChanged("Schedule_Sessions")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedule_Sessions As Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session) = New Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Schedule_Session in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Session
    '''ID_Schedule
    '''Day
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Schedule_Sessions"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Session", "ID_Schedule", "Day")>  _
    Partial Public Class Schedule_Session
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Schedule_Session object.
        '''</summary>
        '''<param name="iD_Session">Initial value of ID_Session.</param>
        '''<param name="iD_Schedule">Initial value of ID_Schedule.</param>
        '''<param name="day">Initial value of Day.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSchedule_Session(ByVal iD_Session As Integer, ByVal iD_Schedule As Integer, ByVal day As String) As Schedule_Session
            Dim schedule_Session As Schedule_Session = New Schedule_Session()
            schedule_Session.ID_Session = iD_Session
            schedule_Session.ID_Schedule = iD_Schedule
            schedule_Session.Day = day
            Return schedule_Session
        End Function
        '''<summary>
        '''There are no comments for Property ID_Session in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Session() As Integer
            Get
                Return Me._ID_Session
            End Get
            Set
                Me.OnID_SessionChanging(value)
                If Object.Equals(Me.ID_Session, value) Then
                    Return
                End If
                Me._ID_Session = value
                Me.OnID_SessionChanged
                Me.OnPropertyChanged("ID_Session")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Session As Integer
        Partial Private Sub OnID_SessionChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_SessionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Schedule in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Schedule() As Integer
            Get
                Return Me._ID_Schedule
            End Get
            Set
                Me.OnID_ScheduleChanging(value)
                If Object.Equals(Me.ID_Schedule, value) Then
                    Return
                End If
                Me._ID_Schedule = value
                Me.OnID_ScheduleChanged
                Me.OnPropertyChanged("ID_Schedule")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Schedule As Integer
        Partial Private Sub OnID_ScheduleChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_ScheduleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Day in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Day() As String
            Get
                Return Me._Day
            End Get
            Set
                Me.OnDayChanging(value)
                If Object.Equals(Me.Day, value) Then
                    Return
                End If
                Me._Day = value
                Me.OnDayChanged
                Me.OnPropertyChanged("Day")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Day As String
        Partial Private Sub OnDayChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnDayChanged()
        End Sub
        '''<summary>
        '''There are no comments for Schedule in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Schedule() As Schedule
            Get
                Me.__Schedule.EnsureValueInitialized
                Return Me._Schedule
            End Get
            Set
                Dim previous As Schedule = Me.Schedule
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Schedule = Nothing
                    Me.__Schedule.OnValueSet
                    previous.Schedule_Sessions.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Schedule = value.ID_Schedule
                    Else
                        Me.ID_Schedule = CType(Nothing, Integer)
                    End If
                End If
                Me._Schedule = value
                Me.__Schedule.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Schedule_Sessions.Add(Me)
                End If
                Me.___OnPropertyChanged("Schedule")
                Me.OnPropertyChanged("Schedule")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedule As Schedule
        '''<summary>
        '''There are no comments for Session in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Session() As Session
            Get
                Me.__Session.EnsureValueInitialized
                Return Me._Session
            End Get
            Set
                Dim previous As Session = Me.Session
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Session = Nothing
                    Me.__Session.OnValueSet
                    previous.Schedule_Sessions.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Session = value.ID_Session
                    Else
                        Me.ID_Session = CType(Nothing, Integer)
                    End If
                End If
                Me._Session = value
                Me.__Session.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Schedule_Sessions.Add(Me)
                End If
                Me.___OnPropertyChanged("Session")
                Me.OnPropertyChanged("Session")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Session As Session
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Session in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Session
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Sessions"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Session")>  _
    Partial Public Class Session
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Session object.
        '''</summary>
        '''<param name="iD_Session">Initial value of ID_Session.</param>
        '''<param name="time_Start">Initial value of Time_Start.</param>
        '''<param name="time_End">Initial value of Time_End.</param>
        '''<param name="name">Initial value of Name.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateSession(ByVal iD_Session As Integer, ByVal time_Start As Global.System.TimeSpan, ByVal time_End As Global.System.TimeSpan, ByVal name As String) As Session
            Dim session As Session = New Session()
            session.ID_Session = iD_Session
            session.Time_Start = time_Start
            session.Time_End = time_End
            session.Name = name
            Return session
        End Function
        '''<summary>
        '''There are no comments for Property ID_Session in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Session() As Integer
            Get
                Return Me._ID_Session
            End Get
            Set
                Me.OnID_SessionChanging(value)
                If Object.Equals(Me.ID_Session, value) Then
                    Return
                End If
                Me._ID_Session = value
                Me.OnID_SessionChanged
                Me.OnPropertyChanged("ID_Session")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Session As Integer
        Partial Private Sub OnID_SessionChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_SessionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Time_Start in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Time_Start() As Global.System.TimeSpan
            Get
                Return Me._Time_Start
            End Get
            Set
                Me.OnTime_StartChanging(value)
                If Object.Equals(Me.Time_Start, value) Then
                    Return
                End If
                Me._Time_Start = value
                Me.OnTime_StartChanged
                Me.OnPropertyChanged("Time_Start")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Time_Start As Global.System.TimeSpan
        Partial Private Sub OnTime_StartChanging(ByVal value As Global.System.TimeSpan)
        End Sub
        Partial Private Sub OnTime_StartChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Time_End in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Time_End() As Global.System.TimeSpan
            Get
                Return Me._Time_End
            End Get
            Set
                Me.OnTime_EndChanging(value)
                If Object.Equals(Me.Time_End, value) Then
                    Return
                End If
                Me._Time_End = value
                Me.OnTime_EndChanged
                Me.OnPropertyChanged("Time_End")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Time_End As Global.System.TimeSpan
        Partial Private Sub OnTime_EndChanging(ByVal value As Global.System.TimeSpan)
        End Sub
        Partial Private Sub OnTime_EndChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                If Object.Equals(Me.Name, value) Then
                    Return
                End If
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ID_Teacher in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Teacher() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ID_Teacher
            End Get
            Set
                Me.OnID_TeacherChanging(value)
                If Object.Equals(Me.ID_Teacher, value) Then
                    Return
                End If
                Me._ID_Teacher = value
                Me.OnID_TeacherChanged
                Me.OnPropertyChanged("ID_Teacher")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Teacher As Global.System.Nullable(Of Integer)
        Partial Private Sub OnID_TeacherChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnID_TeacherChanged()
        End Sub
        '''<summary>
        '''There are no comments for Schedule_Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Schedule_Sessions() As Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session)
            Get
                Me.__Schedule_Sessions.EnsureValueInitialized
                Return Me._Schedule_Sessions
            End Get
            Set
                Me._Schedule_Sessions = value
                Me.OnPropertyChanged("Schedule_Sessions")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Schedule_Sessions As Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session) = New Global.System.Data.Services.Client.DataServiceCollection(Of Schedule_Session)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        '''<summary>
        '''There are no comments for Teacher in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Teacher() As Teacher
            Get
                Me.__Teacher.EnsureValueInitialized
                Return Me._Teacher
            End Get
            Set
                Dim previous As Teacher = Me.Teacher
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Teacher = Nothing
                    Me.__Teacher.OnValueSet
                    previous.Sessions.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.ID_Teacher = value.ID_Teacher
                    Else
                        Me.ID_Teacher = CType(Nothing, Global.System.Nullable(Of Integer))
                    End If
                End If
                Me._Teacher = value
                Me.__Teacher.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__Sessions.Add(Me)
                End If
                Me.___OnPropertyChanged("Teacher")
                Me.OnPropertyChanged("Teacher")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Teacher As Teacher
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for LightSwitchApplication.Teacher in the schema.
    '''</summary>
    '''<KeyProperties>
    '''ID_Teacher
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Teachers"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("ID_Teacher")>  _
    Partial Public Class Teacher
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Teacher object.
        '''</summary>
        '''<param name="iD_Teacher">Initial value of ID_Teacher.</param>
        '''<param name="name">Initial value of Name.</param>
        '''<param name="phone_no">Initial value of Phone_no.</param>
        '''<param name="salary">Initial value of salary.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateTeacher(ByVal iD_Teacher As Integer, ByVal name As String, ByVal phone_no As Integer, ByVal salary As Integer) As Teacher
            Dim teacher As Teacher = New Teacher()
            teacher.ID_Teacher = iD_Teacher
            teacher.Name = name
            teacher.Phone_no = phone_no
            teacher.salary = salary
            Return teacher
        End Function
        '''<summary>
        '''There are no comments for Property ID_Teacher in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ID_Teacher() As Integer
            Get
                Return Me._ID_Teacher
            End Get
            Set
                Me.OnID_TeacherChanging(value)
                If Object.Equals(Me.ID_Teacher, value) Then
                    Return
                End If
                Me._ID_Teacher = value
                Me.OnID_TeacherChanged
                Me.OnPropertyChanged("ID_Teacher")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ID_Teacher As Integer
        Partial Private Sub OnID_TeacherChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnID_TeacherChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                If Object.Equals(Me.Name, value) Then
                    Return
                End If
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Phone_no in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Phone_no() As Integer
            Get
                Return Me._Phone_no
            End Get
            Set
                Me.OnPhone_noChanging(value)
                If Object.Equals(Me.Phone_no, value) Then
                    Return
                End If
                Me._Phone_no = value
                Me.OnPhone_noChanged
                Me.OnPropertyChanged("Phone_no")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Phone_no As Integer
        Partial Private Sub OnPhone_noChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnPhone_noChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property salary in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property salary() As Integer
            Get
                Return Me._salary
            End Get
            Set
                Me.OnsalaryChanging(value)
                If Object.Equals(Me.salary, value) Then
                    Return
                End If
                Me._salary = value
                Me.OnsalaryChanged
                Me.OnPropertyChanged("salary")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _salary As Integer
        Partial Private Sub OnsalaryChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnsalaryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Sessions in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Sessions() As Global.System.Data.Services.Client.DataServiceCollection(Of Session)
            Get
                Me.__Sessions.EnsureValueInitialized
                Return Me._Sessions
            End Get
            Set
                Me._Sessions = value
                Me.OnPropertyChanged("Sessions")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Sessions As Global.System.Data.Services.Client.DataServiceCollection(Of Session) = New Global.System.Data.Services.Client.DataServiceCollection(Of Session)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
