'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication

    #Region "Data Services"
    
    ''' <summary>
    ''' Provides members to query and update data in the IS_projectData datasource.
    ''' </summary>
    Public NotInheritable Partial Class IS_projectDataService
        Inherits Global.LightSwitchApplication.IS_projectData
    
        #Region "Constructors"
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            MyBase.New()
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.LightSwitchApplication.Application
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Server Interceptions Points"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Inserting(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Inserted(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Updating(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Updated(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Deleting(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Deleted(ByVal entity As Global.LightSwitchApplication.Child)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Validate(ByVal entity As Global.LightSwitchApplication.Child, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Children_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Child, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Inserting(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Inserted(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Updating(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Updated(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Deleting(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Deleted(ByVal entity As Global.LightSwitchApplication.Classroom)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Validate(ByVal entity As Global.LightSwitchApplication.Classroom, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Classrooms_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Classroom, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Inserting(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Inserted(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Updating(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Updated(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Deleting(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Deleted(ByVal entity As Global.LightSwitchApplication.Level)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Validate(ByVal entity As Global.LightSwitchApplication.Level, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Levels_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Level, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Inserting(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Inserted(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Updating(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Updated(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Deleting(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Deleted(ByVal entity As Global.LightSwitchApplication.Parent)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Validate(ByVal entity As Global.LightSwitchApplication.Parent, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Parents_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Parent, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Inserting(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Inserted(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Updating(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Updated(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Deleting(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Deleted(ByVal entity As Global.LightSwitchApplication.Payment)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Validate(ByVal entity As Global.LightSwitchApplication.Payment, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Payments_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Payment, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Inserting(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Inserted(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Updating(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Updated(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Deleting(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Deleted(ByVal entity As Global.LightSwitchApplication.Schedule)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Validate(ByVal entity As Global.LightSwitchApplication.Schedule, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedules_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedule_Sessions_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedule_Sessions_Validate(ByVal entity As Global.LightSwitchApplication.Schedule_Session, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Schedule_Sessions_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule_Session, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Inserting(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Inserted(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Updating(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Updated(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Deleting(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Deleted(ByVal entity As Global.LightSwitchApplication.Session)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Validate(ByVal entity As Global.LightSwitchApplication.Session, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Sessions_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Session, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_CanInsert(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_CanUpdate(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_CanDelete(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_CanRead(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Inserting(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Inserted(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Updating(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Updated(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Deleting(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Deleted(ByVal entity As Global.LightSwitchApplication.Teacher)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Validate(ByVal entity As Global.LightSwitchApplication.Teacher, ByVal results As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Teachers_Filter(ByRef filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Teacher, Boolean)))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_Executed()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub SaveChanges_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query1_CanExecute(ByRef result As Boolean)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub Query1_Executing()
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query1_PreprocessQuery(ByRef query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Child))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub Query1_Executed(ByVal result As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Child))
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Partial Private Sub Query1_ExecuteFailed(ByVal exception As Global.System.Exception)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executing(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_Executed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Partial Private Sub Query_ExecuteFailed(ByVal queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
        End Sub
    
        #End Region
        
        #Region "Details Class"
    
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        Public MustInherit Shadows Class DetailsClass
         
            Shared Sub New()
            End Sub
    
            Private Sub New()
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __ChildrenEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Child) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Child)( _
                    "Children",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Children_Filter)
            Private Shared Function __Children_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Children_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Children_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Children_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Children_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Children_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Children_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Children_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Children_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Inserting(e)
            End Sub
            Private Shared Sub __Children_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Inserted(e)
            End Sub
            Private Shared Sub __Children_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Updating(e)
            End Sub
            Private Shared Sub __Children_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Updated(e)
            End Sub
            Private Shared Sub __Children_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Deleting(e)
            End Sub
            Private Shared Sub __Children_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child)
                d.Children_Deleted(e)
            End Sub
            Private Shared Sub __Children_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Child, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Children_Validate(e, r)
            End Sub
            Private Shared Function __Children_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Child, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Child, Boolean)) = Nothing
                d.Children_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __ClassroomsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Classroom) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Classroom)( _
                    "Classrooms",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Classrooms_Filter)
            Private Shared Function __Classrooms_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Classrooms_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Classrooms_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Classrooms_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Classrooms_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Classrooms_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Classrooms_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Classrooms_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Classrooms_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Inserting(e)
            End Sub
            Private Shared Sub __Classrooms_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Inserted(e)
            End Sub
            Private Shared Sub __Classrooms_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Updating(e)
            End Sub
            Private Shared Sub __Classrooms_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Updated(e)
            End Sub
            Private Shared Sub __Classrooms_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Deleting(e)
            End Sub
            Private Shared Sub __Classrooms_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom)
                d.Classrooms_Deleted(e)
            End Sub
            Private Shared Sub __Classrooms_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Classroom, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Classrooms_Validate(e, r)
            End Sub
            Private Shared Function __Classrooms_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Classroom, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Classroom, Boolean)) = Nothing
                d.Classrooms_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __LevelsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Level) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Level)( _
                    "Levels",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Levels_Filter)
            Private Shared Function __Levels_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Levels_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Levels_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Levels_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Levels_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Levels_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Levels_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Levels_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Levels_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Inserting(e)
            End Sub
            Private Shared Sub __Levels_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Inserted(e)
            End Sub
            Private Shared Sub __Levels_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Updating(e)
            End Sub
            Private Shared Sub __Levels_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Updated(e)
            End Sub
            Private Shared Sub __Levels_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Deleting(e)
            End Sub
            Private Shared Sub __Levels_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level)
                d.Levels_Deleted(e)
            End Sub
            Private Shared Sub __Levels_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Level, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Levels_Validate(e, r)
            End Sub
            Private Shared Function __Levels_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Level, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Level, Boolean)) = Nothing
                d.Levels_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __ParentsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Parent) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Parent)( _
                    "Parents",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Parents_Filter)
            Private Shared Function __Parents_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Parents_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Parents_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Parents_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Parents_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Parents_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Parents_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Parents_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Parents_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Inserting(e)
            End Sub
            Private Shared Sub __Parents_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Inserted(e)
            End Sub
            Private Shared Sub __Parents_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Updating(e)
            End Sub
            Private Shared Sub __Parents_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Updated(e)
            End Sub
            Private Shared Sub __Parents_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Deleting(e)
            End Sub
            Private Shared Sub __Parents_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent)
                d.Parents_Deleted(e)
            End Sub
            Private Shared Sub __Parents_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Parent, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Parents_Validate(e, r)
            End Sub
            Private Shared Function __Parents_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Parent, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Parent, Boolean)) = Nothing
                d.Parents_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __PaymentsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Payment) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Payment)( _
                    "Payments",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Payments_Filter)
            Private Shared Function __Payments_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Payments_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Payments_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Payments_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Payments_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Payments_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Payments_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Payments_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Payments_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Inserting(e)
            End Sub
            Private Shared Sub __Payments_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Inserted(e)
            End Sub
            Private Shared Sub __Payments_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Updating(e)
            End Sub
            Private Shared Sub __Payments_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Updated(e)
            End Sub
            Private Shared Sub __Payments_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Deleting(e)
            End Sub
            Private Shared Sub __Payments_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment)
                d.Payments_Deleted(e)
            End Sub
            Private Shared Sub __Payments_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Payment, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Payments_Validate(e, r)
            End Sub
            Private Shared Function __Payments_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Payment, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Payment, Boolean)) = Nothing
                d.Payments_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SchedulesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Schedule) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Schedule)( _
                    "Schedules",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedules_Filter)
            Private Shared Function __Schedules_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Schedules_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Schedules_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Schedules_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Schedules_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Schedules_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Schedules_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Schedules_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Schedules_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Inserting(e)
            End Sub
            Private Shared Sub __Schedules_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Inserted(e)
            End Sub
            Private Shared Sub __Schedules_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Updating(e)
            End Sub
            Private Shared Sub __Schedules_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Updated(e)
            End Sub
            Private Shared Sub __Schedules_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Deleting(e)
            End Sub
            Private Shared Sub __Schedules_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule)
                d.Schedules_Deleted(e)
            End Sub
            Private Shared Sub __Schedules_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Schedules_Validate(e, r)
            End Sub
            Private Shared Function __Schedules_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule, Boolean)) = Nothing
                d.Schedules_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Schedule_SessionsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Schedule_Session) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Schedule_Session)( _
                    "Schedule_Sessions",
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedule_Sessions_CanRead, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    Nothing, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedule_Sessions_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Schedule_Sessions_Filter)
            Private Shared Function __Schedule_Sessions_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Schedule_Sessions_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Schedule_Sessions_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Schedule_Session, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Schedule_Sessions_Validate(e, r)
            End Sub
            Private Shared Function __Schedule_Sessions_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule_Session, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Schedule_Session, Boolean)) = Nothing
                d.Schedule_Sessions_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SessionsEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Session) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Session)( _
                    "Sessions",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Sessions_Filter)
            Private Shared Function __Sessions_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Sessions_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Sessions_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Sessions_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Sessions_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Sessions_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Sessions_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Sessions_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Sessions_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Inserting(e)
            End Sub
            Private Shared Sub __Sessions_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Inserted(e)
            End Sub
            Private Shared Sub __Sessions_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Updating(e)
            End Sub
            Private Shared Sub __Sessions_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Updated(e)
            End Sub
            Private Shared Sub __Sessions_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Deleting(e)
            End Sub
            Private Shared Sub __Sessions_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session)
                d.Sessions_Deleted(e)
            End Sub
            Private Shared Sub __Sessions_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Session, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Sessions_Validate(e, r)
            End Sub
            Private Shared Function __Sessions_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Session, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Session, Boolean)) = Nothing
                d.Sessions_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __TeachersEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Teacher) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Teacher)( _
                    "Teachers",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_CanInsert, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_CanUpdate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_CanDelete, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_CanRead, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Inserting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Inserted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Updating, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Updated, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Deleting, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Deleted, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Validate, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Teachers_Filter)
            Private Shared Function __Teachers_CanInsert(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Teachers_CanInsert(result)
                Return result
            End Function
            Private Shared Function __Teachers_CanUpdate(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Teachers_CanUpdate(result)
                Return result
            End Function
            Private Shared Function __Teachers_CanDelete(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Teachers_CanDelete(result)
                Return result
            End Function
            Private Shared Function __Teachers_CanRead(d As Global.LightSwitchApplication.IS_projectDataService) As Boolean
                Dim result As Boolean = True
                d.Teachers_CanRead(result)
                Return result
            End Function
            Private Shared Sub __Teachers_Inserting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Inserting(e)
            End Sub
            Private Shared Sub __Teachers_Inserted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Inserted(e)
            End Sub
            Private Shared Sub __Teachers_Updating(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Updating(e)
            End Sub
            Private Shared Sub __Teachers_Updated(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Updated(e)
            End Sub
            Private Shared Sub __Teachers_Deleting(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Deleting(e)
            End Sub
            Private Shared Sub __Teachers_Deleted(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher)
                d.Teachers_Deleted(e)
            End Sub
            Private Shared Sub __Teachers_Validate(d As Global.LightSwitchApplication.IS_projectDataService, e As Global.LightSwitchApplication.Teacher, r As Global.Microsoft.LightSwitch.EntitySetValidationResultsBuilder)
                d.Teachers_Validate(e, r)
            End Sub
            Private Shared Function __Teachers_Filter(d As Global.LightSwitchApplication.IS_projectDataService) As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Teacher, Boolean))
                Dim filter As Global.System.Linq.Expressions.Expression(Of Global.System.Func(Of Global.LightSwitchApplication.Teacher, Boolean)) = Nothing
                d.Teachers_Filter(filter)
                return filter
            End Function
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __SaveChangesEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.IS_projectDataService) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.OperationEntry(Of Global.LightSwitchApplication.IS_projectDataService)( _
                    "SaveChanges",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__SaveChanges_CanExecute, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__SaveChanges_Executing, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__SaveChanges_Executed, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__SaveChanges_Failed)
            Private Shared Function __SaveChanges_CanExecute(d As Global.LightSwitchApplication.IS_projectDataService, r As Boolean) As Boolean
                d.SaveChanges_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __SaveChanges_Executing(d As Global.LightSwitchApplication.IS_projectDataService, args As Object())
                d.SaveChanges_Executing()
            End Sub
            Private Shared Sub __SaveChanges_Executed(d As Global.LightSwitchApplication.IS_projectDataService, args As Object())
                d.SaveChanges_Executed()
            End Sub
            Private Shared Sub __SaveChanges_Failed(d As Global.LightSwitchApplication.IS_projectDataService, args As Object(), ex As Global.System.Exception)
                d.SaveChanges_ExecuteFailed(ex)
            End Sub
            
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            Private Shared ReadOnly __Query1Entry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Child) = _
                New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry(Of Global.LightSwitchApplication.IS_projectDataService, Global.LightSwitchApplication.Child)( _
                    "Query1",
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query1_CanExecute, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query1_Executing, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query1_Executed, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query1_Failed, _
                    AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query1_PreprocessQuery)
            Private Shared Function __Query1_CanExecute(d As Global.LightSwitchApplication.IS_projectDataService, r As Boolean) As Boolean
                d.Query1_CanExecute(r)
                Return r
            End Function
            Private Shared Sub __Query1_Executing(d As Global.LightSwitchApplication.IS_projectDataService, args As Object())
                d.Query1_Executing()
            End Sub
            Private Shared Sub __Query1_Executed(d As Global.LightSwitchApplication.IS_projectDataService, args As Object())
                d.Query1_Executed(DirectCast(args(0), Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Child)))
            End Sub
            Private Shared Sub __Query1_Failed(d As Global.LightSwitchApplication.IS_projectDataService, args As Object(), ex As Global.System.Exception)
                d.Query1_ExecuteFailed(ex)
            End Sub
            Private Shared Function __Query1_PreprocessQuery(d As Global.LightSwitchApplication.IS_projectDataService, args As Object()) As Global.System.Linq.IQueryable
                Dim query As Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Child) = DirectCast(args(0), Global.System.Linq.IQueryable(Of Global.LightSwitchApplication.Child))
                d.Query1_PreprocessQuery(query)
                Return query
            End Function
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        Private Shared ReadOnly ___QueryEntry As Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.IS_projectDataService) = _
            New Global.Microsoft.LightSwitch.Details.Framework.Server.QueryEntry(Of Global.LightSwitchApplication.IS_projectDataService)( _
                AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query_Executing, _
                AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query_Executed, _
                AddressOf Global.LightSwitchApplication.IS_projectDataService.DetailsClass.__Query_Failed)
        Private Shared Sub __Query_Executing(d As Global.LightSwitchApplication.IS_projectDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutingDescriptor)
            d.Query_Executing(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Executed(d As Global.LightSwitchApplication.IS_projectDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecutedDescriptor)
            d.Query_Executed(queryDescriptor)
        End Sub
        Private Shared Sub __Query_Failed(d As Global.LightSwitchApplication.IS_projectDataService, queryDescriptor As Global.Microsoft.LightSwitch.QueryExecuteFailedDescriptor)
            d.Query_ExecuteFailed(queryDescriptor)
        End Sub
    
        End Class
    
        #End Region
    
    End Class
    
    #End Region

End Namespace
