
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Session = LightSwitchApplication.Session

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Session
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Session, __Session.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Session entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Session))
            MyBase.New(entitySet)
            
            __Session.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Session_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Session_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Session As Integer
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.ID_Session)
            End Get
            Set
                __Session.DetailsClass.SetValue(Me, __Session.DetailsClass.PropertySetProperties.ID_Session, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Session_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Session_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Session_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Time_Start As Global.System.TimeSpan
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.Time_Start)
            End Get
            Set
                __Session.DetailsClass.SetValue(Me, __Session.DetailsClass.PropertySetProperties.Time_Start, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_Start_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_Start_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_Start_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Time_End As Global.System.TimeSpan
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.Time_End)
            End Get
            Set
                __Session.DetailsClass.SetValue(Me, __Session.DetailsClass.PropertySetProperties.Time_End, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_End_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_End_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Time_End_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Name As String
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.Name)
            End Get
            Set
                __Session.DetailsClass.SetValue(Me, __Session.DetailsClass.PropertySetProperties.Name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Schedule_Sessions As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Schedule_Session)
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.Schedule_Sessions)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Schedule_SessionsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Schedule_Session)
            Get
                Return __Session.DetailsClass.GetQuery(Me, __Session.DetailsClass.PropertySetProperties.Schedule_Sessions)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Teacher As Global.LightSwitchApplication.Teacher
            Get
                Return __Session.DetailsClass.GetValue(Me, __Session.DetailsClass.PropertySetProperties.Teacher)
            End Get
            Set
                __Session.DetailsClass.SetValue(Me, __Session.DetailsClass.PropertySetProperties.Teacher, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Teacher_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Teacher_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Teacher_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Session, _
                __Session.DetailsClass, _
                __Session.DetailsClass.IImplementation, _
                __Session.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Session, __Session.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Session, __Session.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Session.DetailsClass.PropertySetProperties.ID_Session
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __SessionEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Session, __Session.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Session, __Session.DetailsClass).Entry( _
                    AddressOf __Session.DetailsClass.__Session_CreateNew, _
                    AddressOf __Session.DetailsClass.__Session_Created, _
                    AddressOf __Session.DetailsClass.__Session_AllowSaveWithErrors)
            Private Shared Function __Session_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Session)) As __Session
                Return New __Session(es)
            End Function
            Private Shared Sub __Session_Created(e As __Session)
                e.Session_Created()
            End Sub
            Private Shared Function __Session_AllowSaveWithErrors(e As __Session) As Boolean
                Dim result As Boolean = False
                e.Session_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Session, __Session.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Session, __Session.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Session.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Session, __Session.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Session As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.ID_Session),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Time_Start As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.Time_Start),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan))
                    End Get
                End Property
                
                Public ReadOnly Property Time_End As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.Time_End),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan))
                    End Get
                End Property
                
                Public ReadOnly Property Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.Name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.Schedule_Sessions),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session))
                    End Get
                End Property
                
                Public ReadOnly Property Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Session.DetailsClass.PropertySetProperties.Teacher),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Session As Integer
                Shadows Property Time_Start As Global.System.TimeSpan
                Shadows Property Time_End As Global.System.TimeSpan
                Shadows Property Name As String
                Shadows ReadOnly Property Schedule_Sessions As Global.System.Collections.IEnumerable
                Shadows Property Teacher As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Session As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer).Entry( _
                        "ID_Session", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_ComputeIsReadOnly, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_Validate, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_GetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_SetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._ID_Session_OnValueChanged)
                Private Shared Sub _ID_Session_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._ID_Session, sf)
                End Sub
                Private Shared Function _ID_Session_ComputeIsReadOnly(e As __Session) As Boolean
                    Dim result As Boolean = False
                    e.ID_Session_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Session_Validate(e As __Session, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Session_Validate(r)
                End Sub
                Private Shared Function _ID_Session_GetImplementationValue(d As __Session.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Session
                End Function
                Private Shared Sub _ID_Session_SetImplementationValue(d As __Session.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Session = v
                End Sub
                Private Shared Sub _ID_Session_OnValueChanged(e As __Session)
                    e.ID_Session_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Time_Start As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Entry( _
                        "Time_Start", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_ComputeIsReadOnly, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_Validate, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_GetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_SetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_Start_OnValueChanged)
                Private Shared Sub _Time_Start_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._Time_Start, sf)
                End Sub
                Private Shared Function _Time_Start_ComputeIsReadOnly(e As __Session) As Boolean
                    Dim result As Boolean = False
                    e.Time_Start_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Time_Start_Validate(e As __Session, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Time_Start_Validate(r)
                End Sub
                Private Shared Function _Time_Start_GetImplementationValue(d As __Session.DetailsClass) As Global.System.TimeSpan
                    Return d.ImplementationEntity.Time_Start
                End Function
                Private Shared Sub _Time_Start_SetImplementationValue(d As __Session.DetailsClass, v As Global.System.TimeSpan)
                    d.ImplementationEntity.Time_Start = v
                End Sub
                Private Shared Sub _Time_Start_OnValueChanged(e As __Session)
                    e.Time_Start_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Time_End As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Entry( _
                        "Time_End", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_ComputeIsReadOnly, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_Validate, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_GetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_SetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Time_End_OnValueChanged)
                Private Shared Sub _Time_End_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._Time_End, sf)
                End Sub
                Private Shared Function _Time_End_ComputeIsReadOnly(e As __Session) As Boolean
                    Dim result As Boolean = False
                    e.Time_End_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Time_End_Validate(e As __Session, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Time_End_Validate(r)
                End Sub
                Private Shared Function _Time_End_GetImplementationValue(d As __Session.DetailsClass) As Global.System.TimeSpan
                    Return d.ImplementationEntity.Time_End
                End Function
                Private Shared Sub _Time_End_SetImplementationValue(d As __Session.DetailsClass, v As Global.System.TimeSpan)
                    d.ImplementationEntity.Time_End = v
                End Sub
                Private Shared Sub _Time_End_OnValueChanged(e As __Session)
                    e.Time_End_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String).Entry( _
                        "Name", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_Validate, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_GetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_SetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Name_OnValueChanged)
                Private Shared Sub _Name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._Name, sf)
                End Sub
                Private Shared Function _Name_ComputeIsReadOnly(e As __Session) As Boolean
                    Dim result As Boolean = False
                    e.Name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Name_Validate(e As __Session, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Name_Validate(r)
                End Sub
                Private Shared Function _Name_GetImplementationValue(d As __Session.DetailsClass) As String
                    Return d.ImplementationEntity.Name
                End Function
                Private Shared Sub _Name_SetImplementationValue(d As __Session.DetailsClass, v As String)
                    d.ImplementationEntity.Name = v
                End Sub
                Private Shared Sub _Name_OnValueChanged(e As __Session)
                    e.Name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Entry( _
                        "Schedule_Sessions", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Schedule_Sessions_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Schedule_Sessions_GetReferencedEntities, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Schedule_Sessions_GetEntityCollection)
                Private Shared Sub _Schedule_Sessions_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._Schedule_Sessions, sf)
                End Sub
                Private Shared Function _Schedule_Sessions_GetReferencedEntities(d As __Session.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Schedule_Session)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Schedule_Session, Global.LightSwitchApplication.Schedule_Session.DetailsClass)(__Session.DetailsClass.PropertySetProperties.Schedule_Sessions, d._Schedule_Sessions)
                End Function
                Private Shared Function _Schedule_Sessions_GetEntityCollection(d As __Session.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Schedule_Sessions
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher).Entry( _
                        "Teacher", _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_Stub, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_ComputeIsReadOnly, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_Validate, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_GetCoreImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_GetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_SetImplementationValue, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_Refresh, _
                        AddressOf __Session.DetailsClass.PropertySetProperties._Teacher_OnValueChanged)
                Private Shared Sub _Teacher_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Session.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher).Data), d As __Session.DetailsClass, sf As Object)
                    c(d, d._Teacher, sf)
                End Sub
                Private Shared Function _Teacher_ComputeIsReadOnly(e As __Session) As Boolean
                    Dim result As Boolean = False
                    e.Teacher_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Teacher_Validate(e As __Session, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Teacher_Validate(r)
                End Sub
                Private Shared Function _Teacher_GetCoreImplementationValue(d as __Session.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Teacher
                End Function
                Private Shared Function _Teacher_GetImplementationValue(d as __Session.DetailsClass) As Global.LightSwitchApplication.Teacher
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Teacher, Global.LightSwitchApplication.Teacher.DetailsClass)(__Session.DetailsClass.PropertySetProperties.Teacher, d._Teacher)
                End Function
                Private Shared Sub _Teacher_SetImplementationValue(d As __Session.DetailsClass, v As Global.LightSwitchApplication.Teacher)
                    d.SetImplementationValue(__Session.DetailsClass.PropertySetProperties.Teacher, d._Teacher, Sub(i, ev) i.Teacher = ev, v)
                End Sub
                Private Shared Sub _Teacher_Refresh(d As __Session.DetailsClass)
                    d.RefreshNavigationProperty(__Session.DetailsClass.PropertySetProperties.Teacher, d._Teacher)
                End Sub
                Private Shared Sub _Teacher_OnValueChanged(e As __Session)
                    e.Teacher_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Session As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Time_Start As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Time_End As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, Global.System.TimeSpan).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Session, __Session.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Session, __Session.DetailsClass, Global.LightSwitchApplication.Teacher).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
