
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Parent = LightSwitchApplication.Parent

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Parent
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Parent, __Parent.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Parent entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Parent))
            MyBase.New(entitySet)
            
            __Parent.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Parent_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Parent_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Parent As Integer
            Get
                Return __Parent.DetailsClass.GetValue(Me, __Parent.DetailsClass.PropertySetProperties.ID_Parent)
            End Get
            Set
                __Parent.DetailsClass.SetValue(Me, __Parent.DetailsClass.PropertySetProperties.ID_Parent, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Parent_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Parent_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Parent_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Name As String
            Get
                Return __Parent.DetailsClass.GetValue(Me, __Parent.DetailsClass.PropertySetProperties.Name)
            End Get
            Set
                __Parent.DetailsClass.SetValue(Me, __Parent.DetailsClass.PropertySetProperties.Name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Adress As String
            Get
                Return __Parent.DetailsClass.GetValue(Me, __Parent.DetailsClass.PropertySetProperties.Adress)
            End Get
            Set
                __Parent.DetailsClass.SetValue(Me, __Parent.DetailsClass.PropertySetProperties.Adress, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Adress_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Adress_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Adress_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Phone As Global.System.Nullable(Of Integer)
            Get
                Return __Parent.DetailsClass.GetValue(Me, __Parent.DetailsClass.PropertySetProperties.Phone)
            End Get
            Set
                __Parent.DetailsClass.SetValue(Me, __Parent.DetailsClass.PropertySetProperties.Phone, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Child)
            Get
                Return __Parent.DetailsClass.GetValue(Me, __Parent.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ChildrenQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Child)
            Get
                Return __Parent.DetailsClass.GetQuery(Me, __Parent.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Parent, _
                __Parent.DetailsClass, _
                __Parent.DetailsClass.IImplementation, _
                __Parent.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Parent, __Parent.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Parent, __Parent.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Parent.DetailsClass.PropertySetProperties.ID_Parent
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ParentEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Parent, __Parent.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Parent, __Parent.DetailsClass).Entry( _
                    AddressOf __Parent.DetailsClass.__Parent_CreateNew, _
                    AddressOf __Parent.DetailsClass.__Parent_Created, _
                    AddressOf __Parent.DetailsClass.__Parent_AllowSaveWithErrors)
            Private Shared Function __Parent_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Parent)) As __Parent
                Return New __Parent(es)
            End Function
            Private Shared Sub __Parent_Created(e As __Parent)
                e.Parent_Created()
            End Sub
            Private Shared Function __Parent_AllowSaveWithErrors(e As __Parent) As Boolean
                Dim result As Boolean = False
                e.Parent_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Parent, __Parent.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Parent, __Parent.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Parent.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Parent, __Parent.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Parent As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Parent.DetailsClass.PropertySetProperties.ID_Parent),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Parent.DetailsClass.PropertySetProperties.Name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Adress As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Parent.DetailsClass.PropertySetProperties.Adress),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Parent.DetailsClass.PropertySetProperties.Phone),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Parent.DetailsClass.PropertySetProperties.Children),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Parent As Integer
                Shadows Property Name As String
                Shadows Property Adress As String
                Shadows Property Phone As Global.System.Nullable(Of Integer)
                Shadows ReadOnly Property Children As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Parent As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer).Entry( _
                        "ID_Parent", _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_Stub, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_ComputeIsReadOnly, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_Validate, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_GetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_SetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._ID_Parent_OnValueChanged)
                Private Shared Sub _ID_Parent_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Parent.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer).Data), d As __Parent.DetailsClass, sf As Object)
                    c(d, d._ID_Parent, sf)
                End Sub
                Private Shared Function _ID_Parent_ComputeIsReadOnly(e As __Parent) As Boolean
                    Dim result As Boolean = False
                    e.ID_Parent_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Parent_Validate(e As __Parent, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Parent_Validate(r)
                End Sub
                Private Shared Function _ID_Parent_GetImplementationValue(d As __Parent.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Parent
                End Function
                Private Shared Sub _ID_Parent_SetImplementationValue(d As __Parent.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Parent = v
                End Sub
                Private Shared Sub _ID_Parent_OnValueChanged(e As __Parent)
                    e.ID_Parent_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Entry( _
                        "Name", _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_Stub, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_Validate, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_GetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_SetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Name_OnValueChanged)
                Private Shared Sub _Name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Parent.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Data), d As __Parent.DetailsClass, sf As Object)
                    c(d, d._Name, sf)
                End Sub
                Private Shared Function _Name_ComputeIsReadOnly(e As __Parent) As Boolean
                    Dim result As Boolean = False
                    e.Name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Name_Validate(e As __Parent, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Name_Validate(r)
                End Sub
                Private Shared Function _Name_GetImplementationValue(d As __Parent.DetailsClass) As String
                    Return d.ImplementationEntity.Name
                End Function
                Private Shared Sub _Name_SetImplementationValue(d As __Parent.DetailsClass, v As String)
                    d.ImplementationEntity.Name = v
                End Sub
                Private Shared Sub _Name_OnValueChanged(e As __Parent)
                    e.Name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Adress As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Entry( _
                        "Adress", _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_Stub, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_ComputeIsReadOnly, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_Validate, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_GetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_SetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Adress_OnValueChanged)
                Private Shared Sub _Adress_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Parent.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Data), d As __Parent.DetailsClass, sf As Object)
                    c(d, d._Adress, sf)
                End Sub
                Private Shared Function _Adress_ComputeIsReadOnly(e As __Parent) As Boolean
                    Dim result As Boolean = False
                    e.Adress_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Adress_Validate(e As __Parent, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Adress_Validate(r)
                End Sub
                Private Shared Function _Adress_GetImplementationValue(d As __Parent.DetailsClass) As String
                    Return d.ImplementationEntity.Adress
                End Function
                Private Shared Sub _Adress_SetImplementationValue(d As __Parent.DetailsClass, v As String)
                    d.ImplementationEntity.Adress = v
                End Sub
                Private Shared Sub _Adress_OnValueChanged(e As __Parent)
                    e.Adress_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "Phone", _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_Stub, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_Validate, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_GetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_SetImplementationValue, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Phone_OnValueChanged)
                Private Shared Sub _Phone_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Parent.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __Parent.DetailsClass, sf As Object)
                    c(d, d._Phone, sf)
                End Sub
                Private Shared Function _Phone_ComputeIsReadOnly(e As __Parent) As Boolean
                    Dim result As Boolean = False
                    e.Phone_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Phone_Validate(e As __Parent, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Phone_Validate(r)
                End Sub
                Private Shared Function _Phone_GetImplementationValue(d As __Parent.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.Phone
                End Function
                Private Shared Sub _Phone_SetImplementationValue(d As __Parent.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.Phone = v
                End Sub
                Private Shared Sub _Phone_OnValueChanged(e As __Parent)
                    e.Phone_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child).Entry( _
                        "Children", _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Children_Stub, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Children_GetReferencedEntities, _
                        AddressOf __Parent.DetailsClass.PropertySetProperties._Children_GetEntityCollection)
                Private Shared Sub _Children_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Parent.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child).Data), d As __Parent.DetailsClass, sf As Object)
                    c(d, d._Children, sf)
                End Sub
                Private Shared Function _Children_GetReferencedEntities(d As __Parent.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Child)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Child, Global.LightSwitchApplication.Child.DetailsClass)(__Parent.DetailsClass.PropertySetProperties.Children, d._Children)
                End Function
                Private Shared Function _Children_GetEntityCollection(d As __Parent.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Children
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Parent As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Adress As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Parent, __Parent.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Parent, __Parent.DetailsClass, Global.LightSwitchApplication.Child).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
