
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Teacher = LightSwitchApplication.Teacher

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Teacher
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Teacher, __Teacher.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Teacher entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Teacher))
            MyBase.New(entitySet)
            
            __Teacher.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Teacher_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Teacher_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Teacher As Integer
            Get
                Return __Teacher.DetailsClass.GetValue(Me, __Teacher.DetailsClass.PropertySetProperties.ID_Teacher)
            End Get
            Set
                __Teacher.DetailsClass.SetValue(Me, __Teacher.DetailsClass.PropertySetProperties.ID_Teacher, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Teacher_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Teacher_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Teacher_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Name As String
            Get
                Return __Teacher.DetailsClass.GetValue(Me, __Teacher.DetailsClass.PropertySetProperties.Name)
            End Get
            Set
                __Teacher.DetailsClass.SetValue(Me, __Teacher.DetailsClass.PropertySetProperties.Name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Phone_no As Integer
            Get
                Return __Teacher.DetailsClass.GetValue(Me, __Teacher.DetailsClass.PropertySetProperties.Phone_no)
            End Get
            Set
                __Teacher.DetailsClass.SetValue(Me, __Teacher.DetailsClass.PropertySetProperties.Phone_no, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_no_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_no_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_no_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property salary As Integer
            Get
                Return __Teacher.DetailsClass.GetValue(Me, __Teacher.DetailsClass.PropertySetProperties.salary)
            End Get
            Set
                __Teacher.DetailsClass.SetValue(Me, __Teacher.DetailsClass.PropertySetProperties.salary, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub salary_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub salary_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub salary_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Sessions As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Session)
            Get
                Return __Teacher.DetailsClass.GetValue(Me, __Teacher.DetailsClass.PropertySetProperties.Sessions)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property SessionsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Session)
            Get
                Return __Teacher.DetailsClass.GetQuery(Me, __Teacher.DetailsClass.PropertySetProperties.Sessions)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Teacher, _
                __Teacher.DetailsClass, _
                __Teacher.DetailsClass.IImplementation, _
                __Teacher.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Teacher, __Teacher.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Teacher, __Teacher.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Teacher.DetailsClass.PropertySetProperties.ID_Teacher
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __TeacherEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Teacher, __Teacher.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Teacher, __Teacher.DetailsClass).Entry( _
                    AddressOf __Teacher.DetailsClass.__Teacher_CreateNew, _
                    AddressOf __Teacher.DetailsClass.__Teacher_Created, _
                    AddressOf __Teacher.DetailsClass.__Teacher_AllowSaveWithErrors)
            Private Shared Function __Teacher_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Teacher)) As __Teacher
                Return New __Teacher(es)
            End Function
            Private Shared Sub __Teacher_Created(e As __Teacher)
                e.Teacher_Created()
            End Sub
            Private Shared Function __Teacher_AllowSaveWithErrors(e As __Teacher) As Boolean
                Dim result As Boolean = False
                e.Teacher_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Teacher, __Teacher.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Teacher, __Teacher.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Teacher.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Teacher, __Teacher.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Teacher.DetailsClass.PropertySetProperties.ID_Teacher),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Teacher.DetailsClass.PropertySetProperties.Name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Phone_no As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Teacher.DetailsClass.PropertySetProperties.Phone_no),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property salary As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Teacher.DetailsClass.PropertySetProperties.salary),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Teacher.DetailsClass.PropertySetProperties.Sessions),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Teacher As Integer
                Shadows Property Name As String
                Shadows Property Phone_no As Integer
                Shadows Property salary As Integer
                Shadows ReadOnly Property Sessions As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry( _
                        "ID_Teacher", _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_Stub, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_ComputeIsReadOnly, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_Validate, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_GetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_SetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._ID_Teacher_OnValueChanged)
                Private Shared Sub _ID_Teacher_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Teacher.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data), d As __Teacher.DetailsClass, sf As Object)
                    c(d, d._ID_Teacher, sf)
                End Sub
                Private Shared Function _ID_Teacher_ComputeIsReadOnly(e As __Teacher) As Boolean
                    Dim result As Boolean = False
                    e.ID_Teacher_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Teacher_Validate(e As __Teacher, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Teacher_Validate(r)
                End Sub
                Private Shared Function _ID_Teacher_GetImplementationValue(d As __Teacher.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Teacher
                End Function
                Private Shared Sub _ID_Teacher_SetImplementationValue(d As __Teacher.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Teacher = v
                End Sub
                Private Shared Sub _ID_Teacher_OnValueChanged(e As __Teacher)
                    e.ID_Teacher_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String).Entry( _
                        "Name", _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_Stub, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_Validate, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_GetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_SetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Name_OnValueChanged)
                Private Shared Sub _Name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Teacher.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String).Data), d As __Teacher.DetailsClass, sf As Object)
                    c(d, d._Name, sf)
                End Sub
                Private Shared Function _Name_ComputeIsReadOnly(e As __Teacher) As Boolean
                    Dim result As Boolean = False
                    e.Name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Name_Validate(e As __Teacher, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Name_Validate(r)
                End Sub
                Private Shared Function _Name_GetImplementationValue(d As __Teacher.DetailsClass) As String
                    Return d.ImplementationEntity.Name
                End Function
                Private Shared Sub _Name_SetImplementationValue(d As __Teacher.DetailsClass, v As String)
                    d.ImplementationEntity.Name = v
                End Sub
                Private Shared Sub _Name_OnValueChanged(e As __Teacher)
                    e.Name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Phone_no As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry( _
                        "Phone_no", _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_Stub, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_ComputeIsReadOnly, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_Validate, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_GetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_SetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Phone_no_OnValueChanged)
                Private Shared Sub _Phone_no_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Teacher.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data), d As __Teacher.DetailsClass, sf As Object)
                    c(d, d._Phone_no, sf)
                End Sub
                Private Shared Function _Phone_no_ComputeIsReadOnly(e As __Teacher) As Boolean
                    Dim result As Boolean = False
                    e.Phone_no_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Phone_no_Validate(e As __Teacher, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Phone_no_Validate(r)
                End Sub
                Private Shared Function _Phone_no_GetImplementationValue(d As __Teacher.DetailsClass) As Integer
                    Return d.ImplementationEntity.Phone_no
                End Function
                Private Shared Sub _Phone_no_SetImplementationValue(d As __Teacher.DetailsClass, v As Integer)
                    d.ImplementationEntity.Phone_no = v
                End Sub
                Private Shared Sub _Phone_no_OnValueChanged(e As __Teacher)
                    e.Phone_no_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly salary As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Entry( _
                        "salary", _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_Stub, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_ComputeIsReadOnly, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_Validate, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_GetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_SetImplementationValue, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._salary_OnValueChanged)
                Private Shared Sub _salary_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Teacher.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data), d As __Teacher.DetailsClass, sf As Object)
                    c(d, d._salary, sf)
                End Sub
                Private Shared Function _salary_ComputeIsReadOnly(e As __Teacher) As Boolean
                    Dim result As Boolean = False
                    e.salary_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _salary_Validate(e As __Teacher, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.salary_Validate(r)
                End Sub
                Private Shared Function _salary_GetImplementationValue(d As __Teacher.DetailsClass) As Integer
                    Return d.ImplementationEntity.salary
                End Function
                Private Shared Sub _salary_SetImplementationValue(d As __Teacher.DetailsClass, v As Integer)
                    d.ImplementationEntity.salary = v
                End Sub
                Private Shared Sub _salary_OnValueChanged(e As __Teacher)
                    e.salary_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session).Entry( _
                        "Sessions", _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Sessions_Stub, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Sessions_GetReferencedEntities, _
                        AddressOf __Teacher.DetailsClass.PropertySetProperties._Sessions_GetEntityCollection)
                Private Shared Sub _Sessions_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Teacher.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session).Data), d As __Teacher.DetailsClass, sf As Object)
                    c(d, d._Sessions, sf)
                End Sub
                Private Shared Function _Sessions_GetReferencedEntities(d As __Teacher.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Session)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Session, Global.LightSwitchApplication.Session.DetailsClass)(__Teacher.DetailsClass.PropertySetProperties.Sessions, d._Sessions)
                End Function
                Private Shared Function _Sessions_GetEntityCollection(d As __Teacher.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Sessions
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Teacher As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Phone_no As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _salary As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Teacher, __Teacher.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Teacher, __Teacher.DetailsClass, Global.LightSwitchApplication.Session).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
