
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Payment = LightSwitchApplication.Payment

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Payment
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Payment, __Payment.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Payment entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Payment))
            MyBase.New(entitySet)
            
            __Payment.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Payment_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Payment_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Pay As Integer
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.ID_Pay)
            End Get
            Set
                __Payment.DetailsClass.SetValue(Me, __Payment.DetailsClass.PropertySetProperties.ID_Pay, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Pay_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Pay_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Pay_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Child As Integer
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.ID_Child)
            End Get
            Set
                __Payment.DetailsClass.SetValue(Me, __Payment.DetailsClass.PropertySetProperties.ID_Child, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Child_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Child_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Child_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property c_Date As Global.System.Nullable(Of Date)
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.c_Date)
            End Get
            Set
                __Payment.DetailsClass.SetValue(Me, __Payment.DetailsClass.PropertySetProperties.c_Date, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub c_Date_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub c_Date_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub c_Date_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Total_Fees As Global.System.Nullable(Of Integer)
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.Total_Fees)
            End Get
            Set
                __Payment.DetailsClass.SetValue(Me, __Payment.DetailsClass.PropertySetProperties.Total_Fees, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Total_Fees_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Total_Fees_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Total_Fees_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Payment1 As Global.System.Nullable(Of Integer)
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.Payment1)
            End Get
            Set
                __Payment.DetailsClass.SetValue(Me, __Payment.DetailsClass.PropertySetProperties.Payment1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Payment1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Payment1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Payment1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Child)
            Get
                Return __Payment.DetailsClass.GetValue(Me, __Payment.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ChildrenQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Child)
            Get
                Return __Payment.DetailsClass.GetQuery(Me, __Payment.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Payment, _
                __Payment.DetailsClass, _
                __Payment.DetailsClass.IImplementation, _
                __Payment.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Payment, __Payment.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Payment, __Payment.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Payment.DetailsClass.PropertySetProperties.ID_Pay
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __PaymentEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Payment, __Payment.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Payment, __Payment.DetailsClass).Entry( _
                    AddressOf __Payment.DetailsClass.__Payment_CreateNew, _
                    AddressOf __Payment.DetailsClass.__Payment_Created, _
                    AddressOf __Payment.DetailsClass.__Payment_AllowSaveWithErrors)
            Private Shared Function __Payment_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Payment)) As __Payment
                Return New __Payment(es)
            End Function
            Private Shared Sub __Payment_Created(e As __Payment)
                e.Payment_Created()
            End Sub
            Private Shared Function __Payment_AllowSaveWithErrors(e As __Payment) As Boolean
                Dim result As Boolean = False
                e.Payment_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Payment, __Payment.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Payment, __Payment.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Payment.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Payment, __Payment.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Pay As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.ID_Pay),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property ID_Child As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.ID_Child),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property c_Date As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.c_Date),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date)))
                    End Get
                End Property
                
                Public ReadOnly Property Total_Fees As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.Total_Fees),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property Payment1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.Payment1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Payment.DetailsClass.PropertySetProperties.Children),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Pay As Integer
                Shadows Property ID_Child As Integer
                Shadows Property c_Date As Global.System.Nullable(Of Date)
                Shadows Property Total_Fees As Global.System.Nullable(Of Integer)
                Shadows Property Payment1 As Global.System.Nullable(Of Integer)
                Shadows ReadOnly Property Children As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Pay As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Entry( _
                        "ID_Pay", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_ComputeIsReadOnly, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_Validate, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_GetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_SetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Pay_OnValueChanged)
                Private Shared Sub _ID_Pay_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._ID_Pay, sf)
                End Sub
                Private Shared Function _ID_Pay_ComputeIsReadOnly(e As __Payment) As Boolean
                    Dim result As Boolean = False
                    e.ID_Pay_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Pay_Validate(e As __Payment, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Pay_Validate(r)
                End Sub
                Private Shared Function _ID_Pay_GetImplementationValue(d As __Payment.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Pay
                End Function
                Private Shared Sub _ID_Pay_SetImplementationValue(d As __Payment.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Pay = v
                End Sub
                Private Shared Sub _ID_Pay_OnValueChanged(e As __Payment)
                    e.ID_Pay_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Child As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Entry( _
                        "ID_Child", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_ComputeIsReadOnly, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_Validate, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_GetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_SetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._ID_Child_OnValueChanged)
                Private Shared Sub _ID_Child_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._ID_Child, sf)
                End Sub
                Private Shared Function _ID_Child_ComputeIsReadOnly(e As __Payment) As Boolean
                    Dim result As Boolean = False
                    e.ID_Child_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Child_Validate(e As __Payment, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Child_Validate(r)
                End Sub
                Private Shared Function _ID_Child_GetImplementationValue(d As __Payment.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Child
                End Function
                Private Shared Sub _ID_Child_SetImplementationValue(d As __Payment.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Child = v
                End Sub
                Private Shared Sub _ID_Child_OnValueChanged(e As __Payment)
                    e.ID_Child_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly c_Date As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date)).Entry( _
                        "c_Date", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_ComputeIsReadOnly, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_Validate, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_GetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_SetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._c_Date_OnValueChanged)
                Private Shared Sub _c_Date_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date)).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._c_Date, sf)
                End Sub
                Private Shared Function _c_Date_ComputeIsReadOnly(e As __Payment) As Boolean
                    Dim result As Boolean = False
                    e.c_Date_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _c_Date_Validate(e As __Payment, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.c_Date_Validate(r)
                End Sub
                Private Shared Function _c_Date_GetImplementationValue(d As __Payment.DetailsClass) As Global.System.Nullable(Of Date)
                    Return d.ImplementationEntity.c_Date
                End Function
                Private Shared Sub _c_Date_SetImplementationValue(d As __Payment.DetailsClass, v As Global.System.Nullable(Of Date))
                    d.ImplementationEntity.c_Date = __Payment.DetailsClass.ClearDateTimeKind(v)
                End Sub
                Private Shared Sub _c_Date_OnValueChanged(e As __Payment)
                    e.c_Date_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Total_Fees As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "Total_Fees", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_ComputeIsReadOnly, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_Validate, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_GetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_SetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Total_Fees_OnValueChanged)
                Private Shared Sub _Total_Fees_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._Total_Fees, sf)
                End Sub
                Private Shared Function _Total_Fees_ComputeIsReadOnly(e As __Payment) As Boolean
                    Dim result As Boolean = False
                    e.Total_Fees_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Total_Fees_Validate(e As __Payment, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Total_Fees_Validate(r)
                End Sub
                Private Shared Function _Total_Fees_GetImplementationValue(d As __Payment.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.Total_Fees
                End Function
                Private Shared Sub _Total_Fees_SetImplementationValue(d As __Payment.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.Total_Fees = v
                End Sub
                Private Shared Sub _Total_Fees_OnValueChanged(e As __Payment)
                    e.Total_Fees_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Payment1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "Payment1", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_ComputeIsReadOnly, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_Validate, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_GetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_SetImplementationValue, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Payment1_OnValueChanged)
                Private Shared Sub _Payment1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._Payment1, sf)
                End Sub
                Private Shared Function _Payment1_ComputeIsReadOnly(e As __Payment) As Boolean
                    Dim result As Boolean = False
                    e.Payment1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Payment1_Validate(e As __Payment, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Payment1_Validate(r)
                End Sub
                Private Shared Function _Payment1_GetImplementationValue(d As __Payment.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.Payment1
                End Function
                Private Shared Sub _Payment1_SetImplementationValue(d As __Payment.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.Payment1 = v
                End Sub
                Private Shared Sub _Payment1_OnValueChanged(e As __Payment)
                    e.Payment1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child).Entry( _
                        "Children", _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Children_Stub, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Children_GetReferencedEntities, _
                        AddressOf __Payment.DetailsClass.PropertySetProperties._Children_GetEntityCollection)
                Private Shared Sub _Children_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Payment.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child).Data), d As __Payment.DetailsClass, sf As Object)
                    c(d, d._Children, sf)
                End Sub
                Private Shared Function _Children_GetReferencedEntities(d As __Payment.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Child)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Child, Global.LightSwitchApplication.Child.DetailsClass)(__Payment.DetailsClass.PropertySetProperties.Children, d._Children)
                End Function
                Private Shared Function _Children_GetEntityCollection(d As __Payment.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Children
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Pay As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Child As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _c_Date As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Date)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Total_Fees As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Payment1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Payment, __Payment.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Payment, __Payment.DetailsClass, Global.LightSwitchApplication.Child).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
