
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Schedule = LightSwitchApplication.Schedule

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Schedule
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Schedule, __Schedule.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Schedule entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Schedule))
            MyBase.New(entitySet)
            
            __Schedule.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Schedule_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Schedule_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Schedule As Integer
            Get
                Return __Schedule.DetailsClass.GetValue(Me, __Schedule.DetailsClass.PropertySetProperties.ID_Schedule)
            End Get
            Set
                __Schedule.DetailsClass.SetValue(Me, __Schedule.DetailsClass.PropertySetProperties.ID_Schedule, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Schedule_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Schedule_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Schedule_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Name As Global.System.Nullable(Of Integer)
            Get
                Return __Schedule.DetailsClass.GetValue(Me, __Schedule.DetailsClass.PropertySetProperties.Name)
            End Get
            Set
                __Schedule.DetailsClass.SetValue(Me, __Schedule.DetailsClass.PropertySetProperties.Name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Classrooms As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Classroom)
            Get
                Return __Schedule.DetailsClass.GetValue(Me, __Schedule.DetailsClass.PropertySetProperties.Classrooms)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ClassroomsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Classroom)
            Get
                Return __Schedule.DetailsClass.GetQuery(Me, __Schedule.DetailsClass.PropertySetProperties.Classrooms)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Schedule_Sessions As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Schedule_Session)
            Get
                Return __Schedule.DetailsClass.GetValue(Me, __Schedule.DetailsClass.PropertySetProperties.Schedule_Sessions)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Schedule_SessionsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Schedule_Session)
            Get
                Return __Schedule.DetailsClass.GetQuery(Me, __Schedule.DetailsClass.PropertySetProperties.Schedule_Sessions)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Schedule, _
                __Schedule.DetailsClass, _
                __Schedule.DetailsClass.IImplementation, _
                __Schedule.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Schedule, __Schedule.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Schedule, __Schedule.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Schedule.DetailsClass.PropertySetProperties.ID_Schedule
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ScheduleEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Schedule, __Schedule.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Schedule, __Schedule.DetailsClass).Entry( _
                    AddressOf __Schedule.DetailsClass.__Schedule_CreateNew, _
                    AddressOf __Schedule.DetailsClass.__Schedule_Created, _
                    AddressOf __Schedule.DetailsClass.__Schedule_AllowSaveWithErrors)
            Private Shared Function __Schedule_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Schedule)) As __Schedule
                Return New __Schedule(es)
            End Function
            Private Shared Sub __Schedule_Created(e As __Schedule)
                e.Schedule_Created()
            End Sub
            Private Shared Function __Schedule_AllowSaveWithErrors(e As __Schedule) As Boolean
                Dim result As Boolean = False
                e.Schedule_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Schedule, __Schedule.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Schedule, __Schedule.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Schedule.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Schedule, __Schedule.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Schedule.DetailsClass.PropertySetProperties.ID_Schedule),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Schedule.DetailsClass.PropertySetProperties.Name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property Classrooms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Schedule.DetailsClass.PropertySetProperties.Classrooms),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom))
                    End Get
                End Property
                
                Public ReadOnly Property Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Schedule.DetailsClass.PropertySetProperties.Schedule_Sessions),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Schedule As Integer
                Shadows Property Name As Global.System.Nullable(Of Integer)
                Shadows ReadOnly Property Classrooms As Global.System.Collections.IEnumerable
                Shadows ReadOnly Property Schedule_Sessions As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer).Entry( _
                        "ID_Schedule", _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_Stub, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_ComputeIsReadOnly, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_Validate, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_GetImplementationValue, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_SetImplementationValue, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._ID_Schedule_OnValueChanged)
                Private Shared Sub _ID_Schedule_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Schedule.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer).Data), d As __Schedule.DetailsClass, sf As Object)
                    c(d, d._ID_Schedule, sf)
                End Sub
                Private Shared Function _ID_Schedule_ComputeIsReadOnly(e As __Schedule) As Boolean
                    Dim result As Boolean = False
                    e.ID_Schedule_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Schedule_Validate(e As __Schedule, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Schedule_Validate(r)
                End Sub
                Private Shared Function _ID_Schedule_GetImplementationValue(d As __Schedule.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Schedule
                End Function
                Private Shared Sub _ID_Schedule_SetImplementationValue(d As __Schedule.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Schedule = v
                End Sub
                Private Shared Sub _ID_Schedule_OnValueChanged(e As __Schedule)
                    e.ID_Schedule_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "Name", _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_Stub, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_Validate, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_GetImplementationValue, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_SetImplementationValue, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Name_OnValueChanged)
                Private Shared Sub _Name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Schedule.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __Schedule.DetailsClass, sf As Object)
                    c(d, d._Name, sf)
                End Sub
                Private Shared Function _Name_ComputeIsReadOnly(e As __Schedule) As Boolean
                    Dim result As Boolean = False
                    e.Name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Name_Validate(e As __Schedule, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Name_Validate(r)
                End Sub
                Private Shared Function _Name_GetImplementationValue(d As __Schedule.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.Name
                End Function
                Private Shared Sub _Name_SetImplementationValue(d As __Schedule.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.Name = v
                End Sub
                Private Shared Sub _Name_OnValueChanged(e As __Schedule)
                    e.Name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Classrooms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom).Entry( _
                        "Classrooms", _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Classrooms_Stub, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Classrooms_GetReferencedEntities, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Classrooms_GetEntityCollection)
                Private Shared Sub _Classrooms_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Schedule.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom).Data), d As __Schedule.DetailsClass, sf As Object)
                    c(d, d._Classrooms, sf)
                End Sub
                Private Shared Function _Classrooms_GetReferencedEntities(d As __Schedule.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Classroom)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Classroom, Global.LightSwitchApplication.Classroom.DetailsClass)(__Schedule.DetailsClass.PropertySetProperties.Classrooms, d._Classrooms)
                End Function
                Private Shared Function _Classrooms_GetEntityCollection(d As __Schedule.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Classrooms
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Entry( _
                        "Schedule_Sessions", _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Schedule_Sessions_Stub, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Schedule_Sessions_GetReferencedEntities, _
                        AddressOf __Schedule.DetailsClass.PropertySetProperties._Schedule_Sessions_GetEntityCollection)
                Private Shared Sub _Schedule_Sessions_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Schedule.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Data), d As __Schedule.DetailsClass, sf As Object)
                    c(d, d._Schedule_Sessions, sf)
                End Sub
                Private Shared Function _Schedule_Sessions_GetReferencedEntities(d As __Schedule.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Schedule_Session)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Schedule_Session, Global.LightSwitchApplication.Schedule_Session.DetailsClass)(__Schedule.DetailsClass.PropertySetProperties.Schedule_Sessions, d._Schedule_Sessions)
                End Function
                Private Shared Function _Schedule_Sessions_GetEntityCollection(d As __Schedule.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Schedule_Sessions
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Schedule, __Schedule.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Classrooms As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Classroom).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Schedule_Sessions As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Schedule, __Schedule.DetailsClass, Global.LightSwitchApplication.Schedule_Session).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
