
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Classroom = LightSwitchApplication.Classroom

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
    Public NotInheritable Partial Class Classroom
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Classroom, __Classroom.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the Classroom entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Classroom))
            MyBase.New(entitySet)
            
            __Classroom.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Classroom_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Classroom_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return Global.LightSwitchApplication.Application.Current
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ID_Class As Integer
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.ID_Class)
            End Get
            Set
                __Classroom.DetailsClass.SetValue(Me, __Classroom.DetailsClass.PropertySetProperties.ID_Class, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Class_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Class_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ID_Class_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Class_name As String
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Class_name)
            End Get
            Set
                __Classroom.DetailsClass.SetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Class_name, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Class_name_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Class_name_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Class_name_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Capacity As Global.System.Nullable(Of Integer)
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Capacity)
            End Get
            Set
                __Classroom.DetailsClass.SetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Capacity, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Capacity_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Capacity_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Capacity_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Child)
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ChildrenQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Child)
            Get
                Return __Classroom.DetailsClass.GetQuery(Me, __Classroom.DetailsClass.PropertySetProperties.Children)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Level As Global.LightSwitchApplication.Level
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Level)
            End Get
            Set
                __Classroom.DetailsClass.SetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Level, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Level_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Level_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Level_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Schedule As Global.LightSwitchApplication.Schedule
            Get
                Return __Classroom.DetailsClass.GetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Schedule)
            End Get
            Set
                __Classroom.DetailsClass.SetValue(Me, __Classroom.DetailsClass.PropertySetProperties.Schedule, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Schedule_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Schedule_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Schedule_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Classroom, _
                __Classroom.DetailsClass, _
                __Classroom.DetailsClass.IImplementation, _
                __Classroom.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Classroom, __Classroom.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Classroom, __Classroom.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Classroom.DetailsClass.PropertySetProperties.ID_Class
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ClassroomEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Classroom, __Classroom.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Classroom, __Classroom.DetailsClass).Entry( _
                    AddressOf __Classroom.DetailsClass.__Classroom_CreateNew, _
                    AddressOf __Classroom.DetailsClass.__Classroom_Created, _
                    AddressOf __Classroom.DetailsClass.__Classroom_AllowSaveWithErrors)
            Private Shared Function __Classroom_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Classroom)) As __Classroom
                Return New __Classroom(es)
            End Function
            Private Shared Sub __Classroom_Created(e As __Classroom)
                e.Classroom_Created()
            End Sub
            Private Shared Function __Classroom_AllowSaveWithErrors(e As __Classroom) As Boolean
                Dim result As Boolean = False
                e.Classroom_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Classroom, __Classroom.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Classroom, __Classroom.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Classroom.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Classroom, __Classroom.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ID_Class As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.ID_Class),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Class_name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.Class_name),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Capacity As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.Capacity),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer)))
                    End Get
                End Property
                
                Public ReadOnly Property Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.Children),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child))
                    End Get
                End Property
                
                Public ReadOnly Property Level As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.Level),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level))
                    End Get
                End Property
                
                Public ReadOnly Property Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Classroom.DetailsClass.PropertySetProperties.Schedule),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property ID_Class As Integer
                Shadows Property Class_name As String
                Shadows Property Capacity As Global.System.Nullable(Of Integer)
                Shadows ReadOnly Property Children As Global.System.Collections.IEnumerable
                Shadows Property Level As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property Schedule As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ID_Class As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer).Entry( _
                        "ID_Class", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_ComputeIsReadOnly, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_Validate, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_GetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_SetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._ID_Class_OnValueChanged)
                Private Shared Sub _ID_Class_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._ID_Class, sf)
                End Sub
                Private Shared Function _ID_Class_ComputeIsReadOnly(e As __Classroom) As Boolean
                    Dim result As Boolean = False
                    e.ID_Class_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ID_Class_Validate(e As __Classroom, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ID_Class_Validate(r)
                End Sub
                Private Shared Function _ID_Class_GetImplementationValue(d As __Classroom.DetailsClass) As Integer
                    Return d.ImplementationEntity.ID_Class
                End Function
                Private Shared Sub _ID_Class_SetImplementationValue(d As __Classroom.DetailsClass, v As Integer)
                    d.ImplementationEntity.ID_Class = v
                End Sub
                Private Shared Sub _ID_Class_OnValueChanged(e As __Classroom)
                    e.ID_Class_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Class_name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String).Entry( _
                        "Class_name", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_ComputeIsReadOnly, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_Validate, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_GetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_SetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Class_name_OnValueChanged)
                Private Shared Sub _Class_name_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._Class_name, sf)
                End Sub
                Private Shared Function _Class_name_ComputeIsReadOnly(e As __Classroom) As Boolean
                    Dim result As Boolean = False
                    e.Class_name_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Class_name_Validate(e As __Classroom, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Class_name_Validate(r)
                End Sub
                Private Shared Function _Class_name_GetImplementationValue(d As __Classroom.DetailsClass) As String
                    Return d.ImplementationEntity.Class_name
                End Function
                Private Shared Sub _Class_name_SetImplementationValue(d As __Classroom.DetailsClass, v As String)
                    d.ImplementationEntity.Class_name = v
                End Sub
                Private Shared Sub _Class_name_OnValueChanged(e As __Classroom)
                    e.Class_name_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Capacity As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer)).Entry( _
                        "Capacity", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_ComputeIsReadOnly, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_Validate, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_GetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_SetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Capacity_OnValueChanged)
                Private Shared Sub _Capacity_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer)).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._Capacity, sf)
                End Sub
                Private Shared Function _Capacity_ComputeIsReadOnly(e As __Classroom) As Boolean
                    Dim result As Boolean = False
                    e.Capacity_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Capacity_Validate(e As __Classroom, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Capacity_Validate(r)
                End Sub
                Private Shared Function _Capacity_GetImplementationValue(d As __Classroom.DetailsClass) As Global.System.Nullable(Of Integer)
                    Return d.ImplementationEntity.Capacity
                End Function
                Private Shared Sub _Capacity_SetImplementationValue(d As __Classroom.DetailsClass, v As Global.System.Nullable(Of Integer))
                    d.ImplementationEntity.Capacity = v
                End Sub
                Private Shared Sub _Capacity_OnValueChanged(e As __Classroom)
                    e.Capacity_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child).Entry( _
                        "Children", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Children_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Children_GetReferencedEntities, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Children_GetEntityCollection)
                Private Shared Sub _Children_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._Children, sf)
                End Sub
                Private Shared Function _Children_GetReferencedEntities(d As __Classroom.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Child)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Child, Global.LightSwitchApplication.Child.DetailsClass)(__Classroom.DetailsClass.PropertySetProperties.Children, d._Children)
                End Function
                Private Shared Function _Children_GetEntityCollection(d As __Classroom.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Children
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Level As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level).Entry( _
                        "Level", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_ComputeIsReadOnly, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_Validate, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_GetCoreImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_GetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_SetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_Refresh, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Level_OnValueChanged)
                Private Shared Sub _Level_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._Level, sf)
                End Sub
                Private Shared Function _Level_ComputeIsReadOnly(e As __Classroom) As Boolean
                    Dim result As Boolean = False
                    e.Level_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Level_Validate(e As __Classroom, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Level_Validate(r)
                End Sub
                Private Shared Function _Level_GetCoreImplementationValue(d as __Classroom.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Level
                End Function
                Private Shared Function _Level_GetImplementationValue(d as __Classroom.DetailsClass) As Global.LightSwitchApplication.Level
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Level, Global.LightSwitchApplication.Level.DetailsClass)(__Classroom.DetailsClass.PropertySetProperties.Level, d._Level)
                End Function
                Private Shared Sub _Level_SetImplementationValue(d As __Classroom.DetailsClass, v As Global.LightSwitchApplication.Level)
                    d.SetImplementationValue(__Classroom.DetailsClass.PropertySetProperties.Level, d._Level, Sub(i, ev) i.Level = ev, v)
                End Sub
                Private Shared Sub _Level_Refresh(d As __Classroom.DetailsClass)
                    d.RefreshNavigationProperty(__Classroom.DetailsClass.PropertySetProperties.Level, d._Level)
                End Sub
                Private Shared Sub _Level_OnValueChanged(e As __Classroom)
                    e.Level_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule).Entry( _
                        "Schedule", _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_Stub, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_ComputeIsReadOnly, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_Validate, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_GetCoreImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_GetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_SetImplementationValue, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_Refresh, _
                        AddressOf __Classroom.DetailsClass.PropertySetProperties._Schedule_OnValueChanged)
                Private Shared Sub _Schedule_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Classroom.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule).Data), d As __Classroom.DetailsClass, sf As Object)
                    c(d, d._Schedule, sf)
                End Sub
                Private Shared Function _Schedule_ComputeIsReadOnly(e As __Classroom) As Boolean
                    Dim result As Boolean = False
                    e.Schedule_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Schedule_Validate(e As __Classroom, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Schedule_Validate(r)
                End Sub
                Private Shared Function _Schedule_GetCoreImplementationValue(d as __Classroom.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Schedule
                End Function
                Private Shared Function _Schedule_GetImplementationValue(d as __Classroom.DetailsClass) As Global.LightSwitchApplication.Schedule
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Schedule, Global.LightSwitchApplication.Schedule.DetailsClass)(__Classroom.DetailsClass.PropertySetProperties.Schedule, d._Schedule)
                End Function
                Private Shared Sub _Schedule_SetImplementationValue(d As __Classroom.DetailsClass, v As Global.LightSwitchApplication.Schedule)
                    d.SetImplementationValue(__Classroom.DetailsClass.PropertySetProperties.Schedule, d._Schedule, Sub(i, ev) i.Schedule = ev, v)
                End Sub
                Private Shared Sub _Schedule_Refresh(d As __Classroom.DetailsClass)
                    d.RefreshNavigationProperty(__Classroom.DetailsClass.PropertySetProperties.Schedule, d._Schedule)
                End Sub
                Private Shared Sub _Schedule_OnValueChanged(e As __Classroom)
                    e.Schedule_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ID_Class As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Class_name As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Capacity As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Classroom, __Classroom.DetailsClass, Global.System.Nullable(Of Integer)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Children As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Child).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Level As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Level).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Schedule As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Classroom, __Classroom.DetailsClass, Global.LightSwitchApplication.Schedule).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
